-- MetaHunt: Beast family DBC enrichment (scales, food validation)
-- AUTO-GENERATED by .tools — do not edit by hand.
-- Source DBC(s): CreatureFamily.dbc, ItemPetFood.dbc
-- Generated: 2026-03-20 13:57 UTC

if not MTH_DS_Families then return end

-- DBC ID=1  PetFoodMask=208  scale=[0.70-1.00]
if MTH_DS_Families["Wolves"] then
  MTH_DS_Families["Wolves"]["dbcId"] = 1
  MTH_DS_Families["Wolves"]["minScale"] = 0.7
  MTH_DS_Families["Wolves"]["maxScale"] = 1.0
  MTH_DS_Families["Wolves"]["minScaleLevel"] = 1
  MTH_DS_Families["Wolves"]["maxScaleLevel"] = 60
  MTH_DS_Families["Wolves"]["foodMask"] = 208
  MTH_DS_Families["Wolves"]["foodDbc"] = {
  "fungus",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=2  PetFoodMask=209  scale=[0.70-1.10]
if MTH_DS_Families["Cats"] then
  MTH_DS_Families["Cats"]["dbcId"] = 2
  MTH_DS_Families["Cats"]["minScale"] = 0.7
  MTH_DS_Families["Cats"]["maxScale"] = 1.1
  MTH_DS_Families["Cats"]["minScaleLevel"] = 1
  MTH_DS_Families["Cats"]["maxScaleLevel"] = 60
  MTH_DS_Families["Cats"]["foodMask"] = 209
  MTH_DS_Families["Cats"]["foodDbc"] = {
  "meat",
  "fungus",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=3  PetFoodMask=203  scale=[0.40-0.60]
if MTH_DS_Families["Spiders"] then
  MTH_DS_Families["Spiders"]["dbcId"] = 3
  MTH_DS_Families["Spiders"]["minScale"] = 0.4
  MTH_DS_Families["Spiders"]["maxScale"] = 0.6
  MTH_DS_Families["Spiders"]["minScaleLevel"] = 1
  MTH_DS_Families["Spiders"]["maxScaleLevel"] = 60
  MTH_DS_Families["Spiders"]["foodMask"] = 203
  MTH_DS_Families["Spiders"]["foodDbc"] = {
  "meat",
  "fish",
  "bread",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=4  PetFoodMask=210  scale=[0.60-1.00]
if MTH_DS_Families["Bears"] then
  MTH_DS_Families["Bears"]["dbcId"] = 4
  MTH_DS_Families["Bears"]["minScale"] = 0.6
  MTH_DS_Families["Bears"]["maxScale"] = 1.0
  MTH_DS_Families["Bears"]["minScaleLevel"] = 1
  MTH_DS_Families["Bears"]["maxScaleLevel"] = 60
  MTH_DS_Families["Bears"]["foodMask"] = 210
  MTH_DS_Families["Bears"]["foodDbc"] = {
  "bread",
  "cheese",
  "fish",
  "fruit",
  "fungus",
  "meat",
  "raw fish",
  "raw meat",
}
end

-- DBC ID=5  PetFoodMask=211  scale=[0.60-1.00]
if MTH_DS_Families["Boars"] then
  MTH_DS_Families["Boars"]["dbcId"] = 5
  MTH_DS_Families["Boars"]["minScale"] = 0.6
  MTH_DS_Families["Boars"]["maxScale"] = 1.0
  MTH_DS_Families["Boars"]["minScaleLevel"] = 1
  MTH_DS_Families["Boars"]["maxScaleLevel"] = 60
  MTH_DS_Families["Boars"]["foodMask"] = 211
  MTH_DS_Families["Boars"]["foodDbc"] = {
  "bread",
  "cheese",
  "fish",
  "fruit",
  "fungus",
  "meat",
  "raw fish",
  "raw meat",
}
end

-- DBC ID=6  PetFoodMask=212  scale=[0.40-0.60]
if MTH_DS_Families["Crocolisks"] then
  MTH_DS_Families["Crocolisks"]["dbcId"] = 6
  MTH_DS_Families["Crocolisks"]["minScale"] = 0.4
  MTH_DS_Families["Crocolisks"]["maxScale"] = 0.6
  MTH_DS_Families["Crocolisks"]["minScaleLevel"] = 1
  MTH_DS_Families["Crocolisks"]["maxScaleLevel"] = 60
  MTH_DS_Families["Crocolisks"]["foodMask"] = 212
  MTH_DS_Families["Crocolisks"]["foodDbc"] = {
  "cheese",
  "fungus",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=7  PetFoodMask=213  scale=[0.50-0.90]
if MTH_DS_Families["Carrion Birds"] then
  MTH_DS_Families["Carrion Birds"]["dbcId"] = 7
  MTH_DS_Families["Carrion Birds"]["minScale"] = 0.5
  MTH_DS_Families["Carrion Birds"]["maxScale"] = 0.9
  MTH_DS_Families["Carrion Birds"]["minScaleLevel"] = 1
  MTH_DS_Families["Carrion Birds"]["maxScaleLevel"] = 60
  MTH_DS_Families["Carrion Birds"]["foodMask"] = 213
  MTH_DS_Families["Carrion Birds"]["foodDbc"] = {
  "meat",
  "cheese",
  "fungus",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=8  PetFoodMask=214  scale=[0.70-1.40]
if MTH_DS_Families["Crabs"] then
  MTH_DS_Families["Crabs"]["dbcId"] = 8
  MTH_DS_Families["Crabs"]["minScale"] = 0.7
  MTH_DS_Families["Crabs"]["maxScale"] = 1.4
  MTH_DS_Families["Crabs"]["minScaleLevel"] = 1
  MTH_DS_Families["Crabs"]["maxScaleLevel"] = 60
  MTH_DS_Families["Crabs"]["foodMask"] = 214
  MTH_DS_Families["Crabs"]["foodDbc"] = {
  "fish",
  "cheese",
  "fungus",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=9  PetFoodMask=215  scale=[0.70-1.00]
if MTH_DS_Families["Gorillas"] then
  MTH_DS_Families["Gorillas"]["dbcId"] = 9
  MTH_DS_Families["Gorillas"]["minScale"] = 0.7
  MTH_DS_Families["Gorillas"]["maxScale"] = 1.0
  MTH_DS_Families["Gorillas"]["minScaleLevel"] = 1
  MTH_DS_Families["Gorillas"]["maxScaleLevel"] = 60
  MTH_DS_Families["Gorillas"]["foodMask"] = 215
  MTH_DS_Families["Gorillas"]["foodDbc"] = {
  "meat",
  "fish",
  "cheese",
  "fungus",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=11  PetFoodMask=217  scale=[0.50-0.80]
if MTH_DS_Families["Raptors"] then
  MTH_DS_Families["Raptors"]["dbcId"] = 11
  MTH_DS_Families["Raptors"]["minScale"] = 0.5
  MTH_DS_Families["Raptors"]["maxScale"] = 0.8
  MTH_DS_Families["Raptors"]["minScaleLevel"] = 1
  MTH_DS_Families["Raptors"]["maxScaleLevel"] = 60
  MTH_DS_Families["Raptors"]["foodMask"] = 217
  MTH_DS_Families["Raptors"]["foodDbc"] = {
  "meat",
  "bread",
  "fungus",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=12  PetFoodMask=218  scale=[0.50-0.80]
if MTH_DS_Families["Tallstriders"] then
  MTH_DS_Families["Tallstriders"]["dbcId"] = 12
  MTH_DS_Families["Tallstriders"]["minScale"] = 0.5
  MTH_DS_Families["Tallstriders"]["maxScale"] = 0.8
  MTH_DS_Families["Tallstriders"]["minScaleLevel"] = 1
  MTH_DS_Families["Tallstriders"]["maxScaleLevel"] = 60
  MTH_DS_Families["Tallstriders"]["foodMask"] = 218
  MTH_DS_Families["Tallstriders"]["foodDbc"] = {
  "fish",
  "bread",
  "fungus",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=20  PetFoodMask=236  scale=[0.70-1.00]
if MTH_DS_Families["Scorpids"] then
  MTH_DS_Families["Scorpids"]["dbcId"] = 20
  MTH_DS_Families["Scorpids"]["minScale"] = 0.7
  MTH_DS_Families["Scorpids"]["maxScale"] = 1.0
  MTH_DS_Families["Scorpids"]["minScaleLevel"] = 1
  MTH_DS_Families["Scorpids"]["maxScaleLevel"] = 60
  MTH_DS_Families["Scorpids"]["foodMask"] = 236
  MTH_DS_Families["Scorpids"]["foodDbc"] = {
  "cheese",
  "bread",
  "fruit",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=21  PetFoodMask=251  scale=[0.50-0.80]
if MTH_DS_Families["Turtles"] then
  MTH_DS_Families["Turtles"]["dbcId"] = 21
  MTH_DS_Families["Turtles"]["minScale"] = 0.5
  MTH_DS_Families["Turtles"]["maxScale"] = 0.8
  MTH_DS_Families["Turtles"]["minScaleLevel"] = 1
  MTH_DS_Families["Turtles"]["maxScaleLevel"] = 60
  MTH_DS_Families["Turtles"]["foodMask"] = 251
  MTH_DS_Families["Turtles"]["foodDbc"] = {
  "meat",
  "fish",
  "bread",
  "fungus",
  "fruit",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=24  PetFoodMask=653  scale=[0.40-0.70]
if MTH_DS_Families["Bats"] then
  MTH_DS_Families["Bats"]["dbcId"] = 24
  MTH_DS_Families["Bats"]["minScale"] = 0.4
  MTH_DS_Families["Bats"]["maxScale"] = 0.7
  MTH_DS_Families["Bats"]["minScaleLevel"] = 1
  MTH_DS_Families["Bats"]["maxScaleLevel"] = 60
  MTH_DS_Families["Bats"]["foodMask"] = 653
  MTH_DS_Families["Bats"]["foodDbc"] = {
  "meat",
  "cheese",
  "bread",
  "raw fish",
}
end

-- DBC ID=25  PetFoodMask=654  scale=[0.70-0.90]
if MTH_DS_Families["Hyenas"] then
  MTH_DS_Families["Hyenas"]["dbcId"] = 25
  MTH_DS_Families["Hyenas"]["minScale"] = 0.7
  MTH_DS_Families["Hyenas"]["maxScale"] = 0.9
  MTH_DS_Families["Hyenas"]["minScaleLevel"] = 1
  MTH_DS_Families["Hyenas"]["maxScaleLevel"] = 60
  MTH_DS_Families["Hyenas"]["foodMask"] = 654
  MTH_DS_Families["Hyenas"]["foodDbc"] = {
  "fish",
  "cheese",
  "bread",
  "raw fish",
}
end

-- DBC ID=26  PetFoodMask=655  scale=[0.50-0.80]
if MTH_DS_Families["Owls"] then
  MTH_DS_Families["Owls"]["dbcId"] = 26
  MTH_DS_Families["Owls"]["minScale"] = 0.5
  MTH_DS_Families["Owls"]["maxScale"] = 0.8
  MTH_DS_Families["Owls"]["minScaleLevel"] = 1
  MTH_DS_Families["Owls"]["maxScaleLevel"] = 60
  MTH_DS_Families["Owls"]["foodMask"] = 655
  MTH_DS_Families["Owls"]["foodDbc"] = {
  "meat",
  "fish",
  "cheese",
  "bread",
  "raw fish",
}
end

-- DBC ID=27  PetFoodMask=656  scale=[0.50-0.70]
if MTH_DS_Families["Wind Serpents"] then
  MTH_DS_Families["Wind Serpents"]["dbcId"] = 27
  MTH_DS_Families["Wind Serpents"]["minScale"] = 0.5
  MTH_DS_Families["Wind Serpents"]["maxScale"] = 0.7
  MTH_DS_Families["Wind Serpents"]["minScaleLevel"] = 1
  MTH_DS_Families["Wind Serpents"]["maxScaleLevel"] = 60
  MTH_DS_Families["Wind Serpents"]["foodMask"] = 656
  MTH_DS_Families["Wind Serpents"]["foodDbc"] = {
  "fungus",
  "raw fish",
}
end

-- DBC ID=35  PetFoodMask=1009  scale=[0.60-0.80]
if MTH_DS_Families["Serpents"] then
  MTH_DS_Families["Serpents"]["dbcId"] = 35
  MTH_DS_Families["Serpents"]["minScale"] = 0.6
  MTH_DS_Families["Serpents"]["maxScale"] = 0.8
  MTH_DS_Families["Serpents"]["minScaleLevel"] = 1
  MTH_DS_Families["Serpents"]["maxScaleLevel"] = 60
  MTH_DS_Families["Serpents"]["foodMask"] = 1009
  MTH_DS_Families["Serpents"]["foodDbc"] = {
  "meat",
  "fungus",
  "fruit",
  "raw meat",
  "raw fish",
}
end

-- DBC ID=36  PetFoodMask=1010  scale=[0.70-0.90]
if MTH_DS_Families["Foxes"] then
  MTH_DS_Families["Foxes"]["dbcId"] = 36
  MTH_DS_Families["Foxes"]["minScale"] = 0.7
  MTH_DS_Families["Foxes"]["maxScale"] = 0.9
  MTH_DS_Families["Foxes"]["minScaleLevel"] = 1
  MTH_DS_Families["Foxes"]["maxScaleLevel"] = 60
  MTH_DS_Families["Foxes"]["foodMask"] = 1010
  MTH_DS_Families["Foxes"]["foodDbc"] = {
  "fish",
  "fungus",
  "fruit",
  "raw meat",
  "raw fish",
}
end
