-- MetaHunt: Stable slot prices
-- AUTO-GENERATED by .tools — do not edit by hand.
-- Source DBC(s): StableSlotPrices.dbc
-- Generated: 2026-03-20 13:57 UTC

if not MTH_DS then MTH_DS = {} end

MTH_DS_StableSlotPrices = {
  [1] = {
    ["cost_copper"] = 500,
    ["cost_gold"]   = 0,
    ["cost_silver"] = 5,
    ["cost_copper_remainder"] = 0,
    ["display"]     = "0g 5s 0c",
    ["acquireMethod"] = "gold",
  },
  [2] = {
    ["cost_copper"] = 50000,
    ["cost_gold"]   = 5,
    ["cost_silver"] = 0,
    ["cost_copper_remainder"] = 0,
    ["display"]     = "5g 0s 0c",
    ["acquireMethod"] = "gold",
  },
  [3] = {
    ["cost_copper"] = 2500000,
    ["cost_gold"]   = 250,
    ["cost_silver"] = 0,
    ["cost_copper_remainder"] = 0,
    ["display"]     = "250g 0s 0c",
    ["acquireMethod"] = "gold",
  },
  [4] = {
    ["cost_copper"] = 0,
    ["cost_gold"]   = 0,
    ["cost_silver"] = 0,
    ["cost_copper_remainder"] = 0,
    ["display"]     = "Shop",
    ["acquireMethod"] = "shop",
  },
}
