-- MetaHunt: Zone DBC enrichment (worldBounds, dbcAreaId, dbcMapId, dbcName)
-- AUTO-GENERATED by .tools — do not edit by hand.
-- Source DBC(s): WorldMapArea.dbc, AreaTable.dbc
-- Generated: 2026-03-17 07:31 UTC

if not MTH_DS_Zones then return end

-- WMA ID=301  map=0  'Stormwind'
if MTH_DS_Zones[1519] then
  MTH_DS_Zones[1519]["dbcAreaId"] = 1519
  MTH_DS_Zones[1519]["dbcMapId"] = 0
  MTH_DS_Zones[1519]["dbcName"] = "Stormwind"
  MTH_DS_Zones[1519]["worldBounds"] = {
  ["left"] = 1722.92,
  ["right"] = -14.58,
  ["top"] = -7995.8301,
  ["bottom"] = -9154.1699,
}
end

-- WMA ID=321  map=1  'Ogrimmar'
if MTH_DS_Zones[1637] then
  MTH_DS_Zones[1637]["dbcAreaId"] = 1637
  MTH_DS_Zones[1637]["dbcMapId"] = 1
  MTH_DS_Zones[1637]["dbcName"] = "Ogrimmar"
  MTH_DS_Zones[1637]["worldBounds"] = {
  ["left"] = -3680.6001,
  ["right"] = -5083.21,
  ["top"] = 2273.8799,
  ["bottom"] = 1338.46,
}
end

-- WMA ID=362  map=1  'ThunderBluff'
if MTH_DS_Zones[1638] then
  MTH_DS_Zones[1638]["dbcAreaId"] = 1638
  MTH_DS_Zones[1638]["dbcMapId"] = 1
  MTH_DS_Zones[1638]["dbcName"] = "ThunderBluff"
  MTH_DS_Zones[1638]["worldBounds"] = {
  ["left"] = 516.67,
  ["right"] = -527.08,
  ["top"] = -850.0,
  ["bottom"] = -1545.83,
}
end

-- WMA ID=381  map=1  'Darnassis'
if MTH_DS_Zones[1657] then
  MTH_DS_Zones[1657]["dbcAreaId"] = 1657
  MTH_DS_Zones[1657]["dbcMapId"] = 1
  MTH_DS_Zones[1657]["dbcName"] = "Darnassis"
  MTH_DS_Zones[1657]["worldBounds"] = {
  ["left"] = 2938.3601,
  ["right"] = 1880.03,
  ["top"] = 10238.3203,
  ["bottom"] = 9532.5898,
}
end

-- WMA ID=382  map=0  'Undercity'
if MTH_DS_Zones[1497] then
  MTH_DS_Zones[1497]["dbcAreaId"] = 1497
  MTH_DS_Zones[1497]["dbcMapId"] = 0
  MTH_DS_Zones[1497]["dbcName"] = "Undercity"
  MTH_DS_Zones[1497]["worldBounds"] = {
  ["left"] = 873.19,
  ["right"] = -86.18,
  ["top"] = 1877.95,
  ["bottom"] = 1237.84,
}
end

-- WMA ID=509  map=0  'AlahThalas'
if MTH_DS_Zones[2040] then
  MTH_DS_Zones[2040]["dbcAreaId"] = 2040
  MTH_DS_Zones[2040]["dbcMapId"] = 0
  MTH_DS_Zones[2040]["dbcName"] = "AlahThalas"
  MTH_DS_Zones[2040]["worldBounds"] = {
  ["left"] = -2169.0,
  ["right"] = -3637.0,
  ["top"] = 4907.0,
  ["bottom"] = 3931.0,
}
end
