-- MetaHunt: WMA (WorldMapArea.dbc) zone reference data
-- AUTO-GENERATED by .tools/migrate_wma.py — do not edit by hand.
-- Source: Haxxor WMA CSV (patch-9.mpq)
--
-- Provides MTH_MAP_PFQ_TO_WMA: pfQ AreaTable ID → WMA ID lookup
-- Used by map-markers.lua to translate GetCurrentMapAreaID() results
-- and by GetCurrentMapID() to return WMA zone IDs for coord matching.
--
-- Provides MTH_DS_WMAZones: WMA ID → worldBounds + pfqAreaId
-- Used for map overlay features without modifying the pfQ-keyed MTH_DS_Zones.

if not MTH_DS then MTH_DS = {} end

-- pfQ AreaTable ID → WMA ID runtime bridge
MTH_MAP_PFQ_TO_WMA = {
  [1] = 27,  -- DunMorogh
  [3] = 17,  -- Badlands
  [4] = 19,  -- BlastedLands
  [8] = 38,  -- SwampOfSorrows
  [10] = 34,  -- Duskwood
  [11] = 40,  -- Wetlands
  [12] = 30,  -- Elwynn
  [14] = 4,  -- Durotar
  [15] = 141,  -- Dustwallow
  [16] = 181,  -- Aszhara
  [17] = 11,  -- Barrens
  [25] = 519,  -- BlackrockMountain
  [28] = 22,  -- WesternPlaguelands
  [33] = 37,  -- Stranglethorn
  [36] = 15,  -- Alterac
  [38] = 35,  -- LochModan
  [40] = 39,  -- Westfall
  [41] = 32,  -- DeadwindPass
  [44] = 36,  -- Redridge
  [45] = 16,  -- Arathi
  [46] = 29,  -- BurningSteppes
  [47] = 26,  -- Hinterlands
  [51] = 28,  -- SearingGorge
  [85] = 20,  -- Tirisfal
  [130] = 21,  -- Silverpine
  [139] = 23,  -- EasternPlaguelands
  [141] = 41,  -- Teldrassil
  [148] = 42,  -- Darkshore
  [209] = 650,  -- ShadowfangKeep
  [215] = 9,  -- Mulgore
  [267] = 24,  -- Hilsbrad
  [331] = 43,  -- Ashenvale
  [357] = 121,  -- Feralas
  [361] = 182,  -- Felwood
  [400] = 61,  -- ThousandNeedles
  [405] = 101,  -- Desolace
  [406] = 81,  -- StonetalonMountains
  [408] = 505,  -- Gillijim
  [409] = 504,  -- Lapidis
  [440] = 161,  -- Tanaris
  [490] = 201,  -- UngoroCrater
  [491] = 641,  -- RazorfenKraul
  [493] = 241,  -- Moonglade
  [616] = 501,  -- Hyjal
  [618] = 281,  -- Winterspring
  [717] = 611,  -- TheStockade
  [718] = 516,  -- WailingCavernsEntrance
  [719] = 609,  -- BlackFathomDeeps
  [721] = 518,  -- GnomereganEntrance
  [722] = 639,  -- RazorfenDowns
  [796] = 520,  -- ScarletMonasteryEntrance
  [876] = 500,  -- GMIsland
  [1176] = 605,  -- ZulFarrak
  [1337] = 521,  -- UldamanEntrance
  [1377] = 261,  -- Silithus
  [1477] = 607,  -- TheTempleOfAtalHakkar
  [1497] = 382,  -- Undercity
  [1519] = 301,  -- Stormwind
  [1537] = 341,  -- Ironforge
  [1581] = 514,  -- DeadminesEntrance
  [1583] = 629,  -- BlackrockSpire
  [1584] = 623,  -- BlackrockDepths
  [1637] = 321,  -- Orgrimmar
  [1638] = 362,  -- ThunderBluff
  [1657] = 381,  -- Darnassus
  [1769] = 700,  -- TimbermawTunnels
  [1941] = 523,  -- CavernsOfTime
  [1977] = 619,  -- ZulGurub
  [2017] = 652,  -- Stratholme
  [2040] = 509,  -- AlahThalas
  [2057] = 648,  -- Scholomance
  [2100] = 517,  -- MaraudonEntrance
  [2159] = 627,  -- OnyxiasLair
  [2257] = 659,  -- DeeprunTram
  [2366] = 663,  -- BlackMorass2f
  [2437] = 603,  -- Ragefire
  [2557] = 689,  -- DireMaulEntrance
  [2597] = 401,  -- AlteracValley
  [2677] = 635,  -- BlackwingLair
  [2717] = 617,  -- MoltenCore
  [3277] = 443,  -- WarsongGulch
  [3358] = 461,  -- ArathiBasin
  [3428] = 654,  -- AhnQiraj
  [3429] = 625,  -- RuinsofAhnQiraj
  [3456] = 667,  -- Naxxramas
  [3457] = 682,  -- UpperKarazhan
  [3478] = 522,  -- AhnQirajEntrance
  [4012] = 502,  -- ScarletEnclave
  [5023] = 503,  -- Sunnyglade
  [5024] = 511,  -- Icepoint
  [5053] = 680,  -- Moomoo
  [5077] = 670,  -- CrescentGrove
  [5086] = 674,  -- KarazhanCrypt
  [5087] = 676,  -- StormwindVault
  [5097] = 678,  -- EmeraldSanctum
  [5103] = 672,  -- HateforgeQuarry
  [5121] = 507,  -- TelAbim
  [5130] = 601,  -- WinterVeilVale
  [5135] = 644,  -- ScarletMonastery2f
  [5136] = 643,  -- ScarletMonastery
  [5138] = 637,  -- TheDeadmines
  [5147] = 655,  -- AhnQiraj2f
  [5148] = 668,  -- Naxxramas2f
  [5153] = 645,  -- ScarletMonastery3f
  [5163] = 646,  -- ScarletMonastery4f
  [5179] = 510,  -- Gilneas
  [5204] = 662,  -- BlackMorass
  [5208] = 665,  -- GilneasCity
  [5225] = 513,  -- ThalassianHighlands
  [5536] = 512,  -- BlackstoneIsland
  [5557] = 683,  -- UpperKarazhan2f
  [5561] = 685,  -- Balor
  [5581] = 686,  -- Northwind
  [5601] = 691,  -- DragonmawRetreat
  [5602] = 684,  -- GrimReaches
  [5628] = 693,  -- StormwroughtRuins
  [5640] = 701,  -- TimbermawEntrance
  [5641] = 698,  -- WindhornCanyon
  [5642] = 699,  -- Moonwhisper
  [5722] = 702,  -- ThornGorge
  [5723] = 657,  -- Karazhan
  [5731] = 705,  -- WindhornCanyonEntrance
  [5734] = 704,  -- FrostmaneHollow
}

-- WMA ID → pfQ AreaTable ID (for fallback lookups)
MTH_MAP_WMA_TO_PFQ = {
  [4] = 14,  -- Durotar
  [9] = 215,  -- Mulgore
  [11] = 17,  -- Barrens
  [15] = 36,  -- Alterac
  [16] = 45,  -- Arathi
  [17] = 3,  -- Badlands
  [19] = 4,  -- BlastedLands
  [20] = 85,  -- Tirisfal
  [21] = 130,  -- Silverpine
  [22] = 28,  -- WesternPlaguelands
  [23] = 139,  -- EasternPlaguelands
  [24] = 267,  -- Hilsbrad
  [26] = 47,  -- Hinterlands
  [27] = 1,  -- DunMorogh
  [28] = 51,  -- SearingGorge
  [29] = 46,  -- BurningSteppes
  [30] = 12,  -- Elwynn
  [32] = 41,  -- DeadwindPass
  [34] = 10,  -- Duskwood
  [35] = 38,  -- LochModan
  [36] = 44,  -- Redridge
  [37] = 33,  -- Stranglethorn
  [38] = 8,  -- SwampOfSorrows
  [39] = 40,  -- Westfall
  [40] = 11,  -- Wetlands
  [41] = 141,  -- Teldrassil
  [42] = 148,  -- Darkshore
  [43] = 331,  -- Ashenvale
  [61] = 400,  -- ThousandNeedles
  [81] = 406,  -- StonetalonMountains
  [101] = 405,  -- Desolace
  [121] = 357,  -- Feralas
  [141] = 15,  -- Dustwallow
  [161] = 440,  -- Tanaris
  [181] = 16,  -- Aszhara
  [182] = 361,  -- Felwood
  [201] = 490,  -- UngoroCrater
  [241] = 493,  -- Moonglade
  [261] = 1377,  -- Silithus
  [281] = 618,  -- Winterspring
  [301] = 1519,  -- Stormwind
  [321] = 1637,  -- Orgrimmar
  [341] = 1537,  -- Ironforge
  [362] = 1638,  -- ThunderBluff
  [381] = 1657,  -- Darnassus
  [382] = 1497,  -- Undercity
  [401] = 2597,  -- AlteracValley
  [443] = 3277,  -- WarsongGulch
  [461] = 3358,  -- ArathiBasin
  [500] = 876,  -- GMIsland
  [501] = 616,  -- Hyjal
  [502] = 4012,  -- ScarletEnclave
  [503] = 5023,  -- Sunnyglade
  [504] = 409,  -- Lapidis
  [505] = 408,  -- Gillijim
  [507] = 5121,  -- TelAbim
  [509] = 2040,  -- AlahThalas
  [510] = 5179,  -- Gilneas
  [511] = 5024,  -- Icepoint
  [512] = 5536,  -- BlackstoneIsland
  [513] = 5225,  -- ThalassianHighlands
  [514] = 1581,  -- DeadminesEntrance
  [516] = 718,  -- WailingCavernsEntrance
  [517] = 2100,  -- MaraudonEntrance
  [518] = 721,  -- GnomereganEntrance
  [519] = 25,  -- BlackrockMountain
  [520] = 796,  -- ScarletMonasteryEntrance
  [521] = 1337,  -- UldamanEntrance
  [522] = 3478,  -- AhnQirajEntrance
  [523] = 1941,  -- CavernsOfTime
  [601] = 5130,  -- WinterVeilVale
  [603] = 2437,  -- Ragefire
  [605] = 1176,  -- ZulFarrak
  [607] = 1477,  -- TheTempleOfAtalHakkar
  [609] = 719,  -- BlackFathomDeeps
  [611] = 717,  -- TheStockade
  [617] = 2717,  -- MoltenCore
  [619] = 1977,  -- ZulGurub
  [623] = 1584,  -- BlackrockDepths
  [625] = 3429,  -- RuinsofAhnQiraj
  [627] = 2159,  -- OnyxiasLair
  [629] = 1583,  -- BlackrockSpire
  [635] = 2677,  -- BlackwingLair
  [637] = 5138,  -- TheDeadmines
  [639] = 722,  -- RazorfenDowns
  [641] = 491,  -- RazorfenKraul
  [643] = 5136,  -- ScarletMonastery
  [644] = 5135,  -- ScarletMonastery2f
  [645] = 5153,  -- ScarletMonastery3f
  [646] = 5163,  -- ScarletMonastery4f
  [648] = 2057,  -- Scholomance
  [650] = 209,  -- ShadowfangKeep
  [652] = 2017,  -- Stratholme
  [654] = 3428,  -- AhnQiraj
  [655] = 5147,  -- AhnQiraj2f
  [657] = 5723,  -- Karazhan
  [659] = 2257,  -- DeeprunTram
  [662] = 5204,  -- BlackMorass
  [663] = 2366,  -- BlackMorass2f
  [665] = 5208,  -- GilneasCity
  [667] = 3456,  -- Naxxramas
  [668] = 5148,  -- Naxxramas2f
  [670] = 5077,  -- CrescentGrove
  [672] = 5103,  -- HateforgeQuarry
  [674] = 5086,  -- KarazhanCrypt
  [676] = 5087,  -- StormwindVault
  [678] = 5097,  -- EmeraldSanctum
  [680] = 5053,  -- Moomoo
  [682] = 3457,  -- UpperKarazhan
  [683] = 5557,  -- UpperKarazhan2f
  [684] = 5602,  -- GrimReaches
  [685] = 5561,  -- Balor
  [686] = 5581,  -- Northwind
  [689] = 2557,  -- DireMaulEntrance
  [691] = 5601,  -- DragonmawRetreat
  [693] = 5628,  -- StormwroughtRuins
  [698] = 5641,  -- WindhornCanyon
  [699] = 5642,  -- Moonwhisper
  [700] = 1769,  -- TimbermawTunnels
  [701] = 5640,  -- TimbermawEntrance
  [702] = 5722,  -- ThornGorge
  [704] = 5734,  -- FrostmaneHollow
  [705] = 5731,  -- WindhornCanyonEntrance
}

-- WMA ID → worldBounds + pfqAreaId (for map overlay and minimap calibration)
MTH_DS_WMAZones = {
  [4] = { pfqAreaId=14, mapId=1, left=-1962.50, right=-7250.00, top=1808.33, bottom=-1716.67, width=5287.50, height=3525.00 },  -- Durotar
  [9] = { pfqAreaId=215, mapId=1, left=2047.92, right=-3089.58, top=-272.92, bottom=-3697.92, width=5137.50, height=3425.00 },  -- Mulgore
  [11] = { pfqAreaId=17, mapId=1, left=2622.92, right=-7510.42, top=1612.50, bottom=-5143.75, width=10133.34, height=6756.25 },  -- Barrens
  [13] = { pfqAreaId=0, mapId=1, left=17066.60, right=-19733.21, top=12799.90, bottom=-11733.30, width=36799.81, height=24533.20 },  -- Kalimdor
  [14] = { pfqAreaId=0, mapId=0, left=16000.00, right=-19199.90, top=7466.60, bottom=-16000.00, width=35199.90, height=23466.60 },  -- Azeroth
  [15] = { pfqAreaId=36, mapId=0, left=783.33, right=-2016.67, top=1500.00, bottom=-366.67, width=2800.00, height=1866.67 },  -- Alterac
  [16] = { pfqAreaId=45, mapId=0, left=-866.67, right=-4466.67, top=-133.33, bottom=-2533.33, width=3600.00, height=2400.00 },  -- Arathi
  [17] = { pfqAreaId=3, mapId=0, left=-2079.17, right=-4566.67, top=-5889.58, bottom=-7547.92, width=2487.50, height=1658.34 },  -- Badlands
  [19] = { pfqAreaId=4, mapId=0, left=-1241.67, right=-4591.67, top=-10566.67, bottom=-12800.00, width=3350.00, height=2233.33 },  -- BlastedLands
  [20] = { pfqAreaId=85, mapId=0, left=3033.33, right=-1485.42, top=3837.50, bottom=825.00, width=4518.75, height=3012.50 },  -- Tirisfal
  [21] = { pfqAreaId=130, mapId=0, left=3450.00, right=-750.00, top=1666.67, bottom=-1133.33, width=4200.00, height=2800.00 },  -- Silverpine
  [22] = { pfqAreaId=28, mapId=0, left=416.67, right=-3883.33, top=3366.67, bottom=500.00, width=4300.00, height=2866.67 },  -- WesternPlaguelands
  [23] = { pfqAreaId=139, mapId=0, left=-2185.42, right=-6056.25, top=3800.00, bottom=1218.75, width=3870.83, height=2581.25 },  -- EasternPlaguelands
  [24] = { pfqAreaId=267, mapId=0, left=1066.67, right=-2133.33, top=400.00, bottom=-1733.33, width=3200.00, height=2133.33 },  -- Hilsbrad
  [26] = { pfqAreaId=47, mapId=0, left=-1575.00, right=-5425.00, top=1466.67, bottom=-1100.00, width=3850.00, height=2566.67 },  -- Hinterlands
  [27] = { pfqAreaId=1, mapId=0, left=1802.08, right=-3122.92, top=-3877.08, bottom=-7160.42, width=4925.00, height=3283.34 },  -- DunMorogh
  [28] = { pfqAreaId=51, mapId=0, left=-322.92, right=-2554.17, top=-6100.00, bottom=-7587.50, width=2231.25, height=1487.50 },  -- SearingGorge
  [29] = { pfqAreaId=46, mapId=0, left=-266.67, right=-3195.83, top=-7031.25, bottom=-8983.33, width=2929.16, height=1952.08 },  -- BurningSteppes
  [30] = { pfqAreaId=12, mapId=0, left=1535.42, right=-1935.42, top=-7939.58, bottom=-10254.17, width=3470.84, height=2314.59 },  -- Elwynn
  [32] = { pfqAreaId=41, mapId=0, left=-833.33, right=-3333.33, top=-9866.67, bottom=-11533.33, width=2500.00, height=1666.66 },  -- DeadwindPass
  [34] = { pfqAreaId=10, mapId=0, left=833.33, right=-1866.67, top=-9716.67, bottom=-11516.67, width=2700.00, height=1800.00 },  -- Duskwood
  [35] = { pfqAreaId=38, mapId=0, left=-1993.75, right=-4752.08, top=-4487.50, bottom=-6327.08, width=2758.33, height=1839.58 },  -- LochModan
  [36] = { pfqAreaId=44, mapId=0, left=-1570.83, right=-3741.67, top=-8575.00, bottom=-10022.92, width=2170.84, height=1447.92 },  -- Redridge
  [37] = { pfqAreaId=33, mapId=0, left=2220.83, right=-4160.42, top=-11168.75, bottom=-15422.92, width=6381.25, height=4254.17 },  -- Stranglethorn
  [38] = { pfqAreaId=8, mapId=0, left=-2222.92, right=-4516.67, top=-9620.83, bottom=-11150.00, width=2293.75, height=1529.17 },  -- SwampOfSorrows
  [39] = { pfqAreaId=40, mapId=0, left=3016.67, right=-483.33, top=-9400.00, bottom=-11733.33, width=3500.00, height=2333.33 },  -- Westfall
  [40] = { pfqAreaId=11, mapId=0, left=-389.58, right=-4525.00, top=-2147.92, bottom=-4904.17, width=4135.42, height=2756.25 },  -- Wetlands
  [41] = { pfqAreaId=141, mapId=1, left=3814.58, right=-1277.08, top=11831.25, bottom=8437.50, width=5091.66, height=3393.75 },  -- Teldrassil
  [42] = { pfqAreaId=148, mapId=1, left=2941.67, right=-3608.33, top=8333.33, bottom=3966.67, width=6550.00, height=4366.66 },  -- Darkshore
  [43] = { pfqAreaId=331, mapId=1, left=1700.00, right=-4066.67, top=4672.92, bottom=829.17, width=5766.67, height=3843.75 },  -- Ashenvale
  [61] = { pfqAreaId=400, mapId=1, left=-433.33, right=-4833.33, top=-3966.67, bottom=-6900.00, width=4400.00, height=2933.33 },  -- ThousandNeedles
  [81] = { pfqAreaId=406, mapId=1, left=3949.00, right=-2069.00, top=3441.00, bottom=-569.00, width=6018.00, height=4010.00 },  -- StonetalonMountains
  [101] = { pfqAreaId=405, mapId=1, left=4233.33, right=-262.50, top=452.08, bottom=-2545.83, width=4495.83, height=2997.91 },  -- Desolace
  [121] = { pfqAreaId=357, mapId=1, left=5441.67, right=-1508.33, top=-2366.67, bottom=-7000.00, width=6950.00, height=4633.33 },  -- Feralas
  [141] = { pfqAreaId=15, mapId=1, left=-975.00, right=-6225.00, top=-2033.33, bottom=-5533.33, width=5250.00, height=3500.00 },  -- Dustwallow
  [161] = { pfqAreaId=440, mapId=1, left=-218.75, right=-7118.75, top=-5875.00, bottom=-10475.00, width=6900.00, height=4600.00 },  -- Tanaris
  [181] = { pfqAreaId=16, mapId=1, left=-3277.08, right=-8347.92, top=5341.67, bottom=1960.42, width=5070.84, height=3381.25 },  -- Aszhara
  [182] = { pfqAreaId=361, mapId=1, left=1641.67, right=-4108.33, top=7133.33, bottom=3300.00, width=5750.00, height=3833.33 },  -- Felwood
  [201] = { pfqAreaId=490, mapId=1, left=533.33, right=-3166.67, top=-5966.67, bottom=-8433.33, width=3700.00, height=2466.66 },  -- UngoroCrater
  [241] = { pfqAreaId=493, mapId=1, left=-1381.25, right=-3689.58, top=8491.67, bottom=6952.08, width=2308.33, height=1539.59 },  -- Moonglade
  [261] = { pfqAreaId=1377, mapId=1, left=2537.50, right=-945.83, top=-5958.33, bottom=-8281.25, width=3483.33, height=2322.92 },  -- Silithus
  [281] = { pfqAreaId=618, mapId=1, left=-316.67, right=-7416.67, top=8533.33, bottom=3800.00, width=7100.00, height=4733.33 },  -- Winterspring
  [301] = { pfqAreaId=1519, mapId=0, left=1722.92, right=-14.58, top=-7995.83, bottom=-9154.17, width=1737.50, height=1158.34 },  -- Stormwind
  [321] = { pfqAreaId=1637, mapId=1, left=-3680.60, right=-5083.21, top=2273.88, bottom=1338.46, width=1402.61, height=935.42 },  -- Orgrimmar
  [341] = { pfqAreaId=1537, mapId=0, left=-713.59, right=-1504.22, top=-4569.24, bottom=-5096.85, width=790.63, height=527.61 },  -- Ironforge
  [362] = { pfqAreaId=1638, mapId=1, left=516.67, right=-527.08, top=-850.00, bottom=-1545.83, width=1043.75, height=695.83 },  -- ThunderBluff
  [381] = { pfqAreaId=1657, mapId=1, left=2938.36, right=1880.03, top=10238.32, bottom=9532.59, width=1058.33, height=705.73 },  -- Darnassus
  [382] = { pfqAreaId=1497, mapId=0, left=873.19, right=-86.18, top=1877.95, bottom=1237.84, width=959.37, height=640.11 },  -- Undercity
  [401] = { pfqAreaId=2597, mapId=30, left=1781.25, right=-2456.25, top=1085.42, bottom=-1739.58, width=4237.50, height=2825.00 },  -- AlteracValley
  [443] = { pfqAreaId=3277, mapId=489, left=2041.67, right=895.83, top=1627.08, bottom=862.50, width=1145.84, height=764.58 },  -- WarsongGulch
  [461] = { pfqAreaId=3358, mapId=529, left=1858.33, right=102.08, top=1508.33, bottom=337.50, width=1756.25, height=1170.83 },  -- ArathiBasin
  [500] = { pfqAreaId=876, mapId=1, left=16748.00, right=15920.00, top=16525.00, bottom=15984.00, width=828.00, height=541.00 },  -- GMIsland
  [501] = { pfqAreaId=616, mapId=1, left=-1080.00, right=-4286.00, top=6125.00, bottom=3983.00, width=3206.00, height=2142.00 },  -- Hyjal
  [502] = { pfqAreaId=4012, mapId=0, left=-4050.00, right=-7209.00, top=3087.00, bottom=979.00, width=3159.00, height=2108.00 },  -- ScarletEnclave
  [503] = { pfqAreaId=5023, mapId=27, left=1013.00, right=-435.00, top=1823.00, bottom=858.00, width=1448.00, height=965.00 },  -- Sunnyglade
  [504] = { pfqAreaId=409, mapId=0, left=4933.33, right=2031.88, top=-11043.48, bottom=-12959.42, width=2901.45, height=1915.94 },  -- Lapidis
  [505] = { pfqAreaId=408, mapId=0, left=4436.22, right=1344.12, top=-12528.71, bottom=-14575.72, width=3092.10, height=2047.01 },  -- Gillijim
  [507] = { pfqAreaId=5121, mapId=1, left=-5179.00, right=-8406.00, top=-7184.00, bottom=-9371.00, width=3227.00, height=2187.00 },  -- TelAbim
  [509] = { pfqAreaId=2040, mapId=0, left=-2169.00, right=-3637.00, top=4907.00, bottom=3931.00, width=1468.00, height=976.00 },  -- AlahThalas
  [510] = { pfqAreaId=5179, mapId=0, left=3253.00, right=-413.00, top=-359.00, bottom=-2801.00, width=3666.00, height=2442.00 },  -- Gilneas
  [511] = { pfqAreaId=5024, mapId=1, left=-5595.00, right=-7203.00, top=14405.00, bottom=13330.00, width=1608.00, height=1075.00 },  -- Icepoint
  [512] = { pfqAreaId=5536, mapId=1, left=-6274.00, right=-8746.00, top=799.00, bottom=-866.00, width=2472.00, height=1665.00 },  -- BlackstoneIsland
  [513] = { pfqAreaId=5225, mapId=0, left=-1005.00, right=-4087.00, top=4952.00, bottom=2891.00, width=3082.00, height=2061.00 },  -- ThalassianHighlands
  [514] = { pfqAreaId=1581, mapId=0, left=1793.18, right=1343.29, top=-11054.94, bottom=-11354.86, width=449.89, height=299.92 },  -- DeadminesEntrance
  [516] = { pfqAreaId=718, mapId=1, left=-1900.87, right=-2473.65, top=-488.64, bottom=-870.49, width=572.78, height=381.85 },  -- WailingCavernsEntrance
  [517] = { pfqAreaId=2100, mapId=1, left=3208.00, right=2384.00, top=-1096.00, bottom=-1646.00, width=824.00, height=550.00 },  -- MaraudonEntrance
  [518] = { pfqAreaId=721, mapId=0, left=1027.64, right=456.45, top=-4806.32, bottom=-5185.46, width=571.19, height=379.14 },  -- GnomereganEntrance
  [519] = { pfqAreaId=25, mapId=0, left=-760.94, right=-1472.50, top=-7327.82, bottom=-7796.50, width=711.56, height=468.68 },  -- BlackrockMountain
  [520] = { pfqAreaId=796, mapId=0, left=-659.96, right=-863.62, top=2947.37, bottom=2812.33, width=203.66, height=135.04 },  -- ScarletMonasteryEntrance
  [521] = { pfqAreaId=1337, mapId=0, left=-2747.15, right=-3310.46, top=-5953.41, bottom=-6329.51, width=563.31, height=376.10 },  -- UldamanEntrance
  [522] = { pfqAreaId=3478, mapId=1, left=3932.67, right=-206.35, top=-8005.20, bottom=-10951.25, width=4139.02, height=2946.05 },  -- AhnQirajEntrance
  [523] = { pfqAreaId=1941, mapId=1, left=-3695.85, right=-5044.09, top=-8023.09, bottom=-8911.18, width=1348.24, height=888.09 },  -- CavernsOfTime
  [601] = { pfqAreaId=5130, mapId=813, left=1916.00, right=484.00, top=-2332.00, bottom=-3309.00, width=1432.00, height=977.00 },  -- WinterVeilVale
  [603] = { pfqAreaId=2437, mapId=389, left=452.87, right=-285.99, top=39.62, bottom=-452.95, width=738.86, height=492.57 },  -- Ragefire
  [605] = { pfqAreaId=1176, mapId=209, left=1625.00, right=241.67, top=2052.08, bottom=1129.17, width=1383.33, height=922.91 },  -- ZulFarrak
  [607] = { pfqAreaId=1477, mapId=109, left=442.76, right=-252.27, top=-255.17, bottom=-718.52, width=695.03, height=463.35 },  -- TheTempleOfAtalHakkar
  [609] = { pfqAreaId=719, mapId=48, left=485.41, right=-736.46, top=-107.91, bottom=-914.33, width=1221.87, height=806.42 },  -- BlackFathomDeeps
  [611] = { pfqAreaId=717, mapId=34, left=189.82, right=-188.33, top=220.63, bottom=-31.47, width=378.15, height=252.10 },  -- TheStockade
  [613] = { pfqAreaId=721, mapId=90, left=863.00, right=-262.00, top=-245.00, bottom=-985.00, width=1125.00, height=740.00 },  -- Gnomeregan
  [615] = { pfqAreaId=1337, mapId=70, left=645.12, right=-248.55, top=204.31, bottom=-391.47, width=893.67, height=595.78 },  -- Uldaman
  [617] = { pfqAreaId=2717, mapId=409, left=-11.00, right=-1506.00, top=1439.00, bottom=456.00, width=1495.00, height=983.00 },  -- MoltenCore
  [619] = { pfqAreaId=1977, mapId=309, left=-612.50, right=-2733.33, top=-11225.00, bottom=-12639.58, width=2120.83, height=1414.58 },  -- ZulGurub
  [621] = { pfqAreaId=2557, mapId=429, left=1007.00, right=-912.00, top=955.00, bottom=-295.00, width=1919.00, height=1250.00 },  -- DireMaul
  [623] = { pfqAreaId=1584, mapId=230, left=875.00, right=-1110.00, top=1513.00, bottom=245.00, width=1985.00, height=1268.00 },  -- BlackrockDepths
  [625] = { pfqAreaId=3429, mapId=509, left=3035.42, right=522.92, top=-8233.33, bottom=-9908.33, width=2512.50, height=1675.00 },  -- RuinsofAhnQiraj
  [627] = { pfqAreaId=2159, mapId=249, left=155.00, right=-366.00, top=86.00, bottom=-262.00, width=521.00, height=348.00 },  -- OnyxiasLair
  [629] = { pfqAreaId=1583, mapId=229, left=10.59, right=-876.25, top=304.40, bottom=-286.83, width=886.84, height=591.23 },  -- BlackrockSpire
  [631] = { pfqAreaId=718, mapId=43, left=790.00, right=-380.00, top=215.00, bottom=-570.00, width=1170.00, height=785.00 },  -- WailingCaverns
  [633] = { pfqAreaId=2100, mapId=349, left=485.41, right=-1626.68, top=1199.76, bottom=-211.13, width=2112.09, height=1410.89 },  -- Maraudon
  [635] = { pfqAreaId=2677, mapId=469, left=-645.00, right=-1422.00, top=-7255.00, bottom=-7760.00, width=777.00, height=505.00 },  -- BlackwingLair
  [637] = { pfqAreaId=5138, mapId=36, left=-322.94, right=-979.53, top=36.93, bottom=-398.04, width=656.59, height=434.97 },  -- TheDeadmines
  [639] = { pfqAreaId=722, mapId=129, left=1271.00, right=390.00, top=2683.00, bottom=2094.00, width=881.00, height=589.00 },  -- RazorfenDowns
  [641] = { pfqAreaId=491, mapId=47, left=2058.92, right=1322.47, top=2349.64, bottom=1858.68, width=736.45, height=490.96 },  -- RazorfenKraul
  [643] = { pfqAreaId=5136, mapId=189, left=1567.97, right=947.99, top=2030.18, bottom=1616.86, width=619.98, height=413.32 },  -- ScarletMonastery
  [644] = { pfqAreaId=5135, mapId=189, left=-162.27, right=-482.46, top=307.37, bottom=93.91, width=320.19, height=213.46 },  -- ScarletMonastery2f
  [645] = { pfqAreaId=5153, mapId=189, left=50.27, right=-562.42, top=2009.10, bottom=1600.64, width=612.69, height=408.46 },  -- ScarletMonastery3f
  [646] = { pfqAreaId=5163, mapId=189, left=1743.99, right=1040.69, top=1281.29, bottom=812.42, width=703.30, height=468.87 },  -- ScarletMonastery4f
  [648] = { pfqAreaId=2057, mapId=289, left=251.41, right=-68.64, top=317.70, bottom=104.33, width=320.05, height=213.37 },  -- Scholomance
  [650] = { pfqAreaId=209, mapId=33, left=2436.00, right=2055.00, top=-61.00, bottom=-315.00, width=381.00, height=254.00 },  -- ShadowfangKeep
  [652] = { pfqAreaId=2017, mapId=329, left=-2639.83, right=-3825.18, top=4163.90, bottom=3374.04, width=1185.35, height=789.86 },  -- Stratholme
  [654] = { pfqAreaId=3428, mapId=531, left=2515.63, right=1538.07, top=-8051.80, bottom=-8703.50, width=977.56, height=651.70 },  -- AhnQiraj
  [655] = { pfqAreaId=5147, mapId=531, left=2915.62, right=138.08, top=-7659.29, bottom=-9510.98, width=2777.54, height=1851.69 },  -- AhnQiraj2f
  [657] = { pfqAreaId=5723, mapId=532, left=-1546.00, right=-2165.00, top=-10789.00, bottom=-11199.00, width=619.00, height=410.00 },  -- Karazhan
  [659] = { pfqAreaId=2257, mapId=369, left=2623.50, right=2311.50, top=95.50, bottom=-112.50, width=312.00, height=208.00 },  -- DeeprunTram
  [662] = { pfqAreaId=5204, mapId=269, left=7338.47, right=6066.48, top=-1247.55, bottom=-2093.03, width=1271.99, height=845.48 },  -- BlackMorass
  [663] = { pfqAreaId=2366, mapId=269, left=7651.85, right=6565.99, top=-1500.47, bottom=-2227.08, width=1085.86, height=726.61 },  -- BlackMorass2f
  [665] = { pfqAreaId=5208, mapId=815, left=3290.32, right=2040.14, top=-760.72, bottom=-1598.16, width=1250.18, height=837.44 },  -- GilneasCity
  [667] = { pfqAreaId=3456, mapId=533, left=-2375.27, right=-4366.96, top=3656.70, bottom=2338.28, width=1991.69, height=1318.42 },  -- Naxxramas
  [668] = { pfqAreaId=5148, mapId=533, left=-4869.36, right=-5521.46, top=3816.56, bottom=3376.89, width=652.10, height=439.67 },  -- Naxxramas2f
  [670] = { pfqAreaId=5077, mapId=802, left=1207.72, right=-1435.49, top=882.98, bottom=-868.18, width=2643.21, height=1751.16 },  -- CrescentGrove
  [672] = { pfqAreaId=5103, mapId=808, left=-3024.33, right=-3776.45, top=-7888.28, bottom=-8398.61, width=752.12, height=510.33 },  -- HateforgeQuarry
  [674] = { pfqAreaId=5086, mapId=800, left=-1302.51, right=-1849.26, top=-10916.17, bottom=-11308.14, width=546.75, height=391.97 },  -- KarazhanCrypt
  [676] = { pfqAreaId=5087, mapId=35, left=314.34, right=-40.16, top=89.30, bottom=-145.44, width=354.50, height=234.74 },  -- StormwindVault
  [678] = { pfqAreaId=5097, mapId=807, left=3939.10, right=2666.00, top=3519.72, bottom=2666.00, width=1273.10, height=853.72 },  -- EmeraldSanctum
  [680] = { pfqAreaId=5053, mapId=801, left=17296.30, right=16288.62, top=17158.52, bottom=16486.73, width=1007.68, height=671.79 },  -- Moomoo
  [682] = { pfqAreaId=3457, mapId=814, left=-1378.00, right=-2201.00, top=-10887.00, bottom=-11436.00, width=823.00, height=549.00 },  -- UpperKarazhan
  [683] = { pfqAreaId=5557, mapId=814, left=-1483.00, right=-4283.00, top=-5800.00, bottom=-7668.00, width=2800.00, height=1868.00 },  -- UpperKarazhan2f
  [684] = { pfqAreaId=5602, mapId=0, left=-2072.00, right=-7459.00, top=-2904.00, bottom=-6488.00, width=5387.00, height=3584.00 },  -- GrimReaches
  [685] = { pfqAreaId=5561, mapId=0, left=4728.00, right=1630.00, top=-7577.00, bottom=-9645.00, width=3098.00, height=2068.00 },  -- Balor
  [686] = { pfqAreaId=5581, mapId=0, left=2258.00, right=-983.00, top=-6327.00, bottom=-8484.00, width=3241.00, height=2157.00 },  -- Northwind
  [689] = { pfqAreaId=2557, mapId=1, left=2014.00, right=690.00, top=-3401.00, bottom=-4270.00, width=1324.00, height=869.00 },  -- DireMaulEntrance
  [691] = { pfqAreaId=5601, mapId=816, left=-3428.00, right=-5062.00, top=-5599.00, bottom=-6672.00, width=1634.00, height=1073.00 },  -- DragonmawRetreat
  [693] = { pfqAreaId=5628, mapId=818, left=-3365.00, right=-5345.00, top=-5424.00, bottom=-6774.00, width=1980.00, height=1350.00 },  -- StormwroughtRuins
  [694] = { pfqAreaId=0, mapId=0, left=0.00, right=0.00, top=0.00, bottom=0.00, width=0.00, height=0.00 },  -- World
  [696] = { pfqAreaId=5640, mapId=819, left=-2991.00, right=-4416.00, top=-7195.00, bottom=-8157.00, width=1425.00, height=962.00 },  -- Timbermaw
  [698] = { pfqAreaId=5641, mapId=820, left=-3184.00, right=-4418.00, top=-7163.00, bottom=-7992.00, width=1234.00, height=829.00 },  -- WindhornCanyon
  [699] = { pfqAreaId=5642, mapId=1, left=-1354.00, right=-9210.00, top=10204.00, bottom=4963.00, width=7856.00, height=5241.00 },  -- Moonwhisper
  [700] = { pfqAreaId=1769, mapId=1, left=-1862.00, right=-2723.00, top=7395.00, bottom=6788.00, width=861.00, height=607.00 },  -- TimbermawTunnels
  [701] = { pfqAreaId=5640, mapId=1, left=-4646.00, right=-5993.00, top=5175.00, bottom=4204.00, width=1347.00, height=971.00 },  -- TimbermawEntrance
  [702] = { pfqAreaId=5722, mapId=821, left=2105.00, right=1058.00, top=2522.00, bottom=1828.00, width=1047.00, height=694.00 },  -- ThornGorge
  [704] = { pfqAreaId=5734, mapId=822, left=-3157.00, right=-4168.00, top=-7453.00, bottom=-8106.00, width=1011.00, height=653.00 },  -- FrostmaneHollow
  [705] = { pfqAreaId=5731, mapId=1, left=-3231.00, right=-3671.00, top=-5053.00, bottom=-5332.00, width=440.00, height=279.00 },  -- WindhornCanyonEntrance
}