-- MetaHunt: Zones present in DBC but not in MTH_DS_Zones (TWoW custom zones)
-- AUTO-GENERATED by .tools — do not edit by hand.
-- Source DBC(s): WorldMapArea.dbc, AreaTable.dbc
-- Generated: 2026-03-20 13:57 UTC

if not MTH_DS_Zones then MTH_DS_Zones = {} end

-- DBC WMA ID=4  MapID=1  'Durotar'
if not MTH_DS_Zones[14] then
  MTH_DS_Zones[14] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 14,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Durotar",
    ["worldBounds"] = { left=-1962.50, right=-7250.00, top=1808.33, bottom=-1716.67 },
    ["names"] = { ["enUS"] = "Durotar", ["esES"] = "Durotar", ["ptBR"] = "Durotar", ["zhCN"] = "杜隆塔尔" },
  }
end

-- DBC WMA ID=9  MapID=1  'Mulgore'
if not MTH_DS_Zones[215] then
  MTH_DS_Zones[215] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 215,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Mulgore",
    ["worldBounds"] = { left=2047.92, right=-3089.58, top=-272.92, bottom=-3697.92 },
    ["names"] = { ["enUS"] = "Mulgore", ["esES"] = "Mulgore", ["ptBR"] = "Mulgore", ["zhCN"] = "莫高雷" },
  }
end

-- DBC WMA ID=11  MapID=1  'Barrens'
if not MTH_DS_Zones[17] then
  MTH_DS_Zones[17] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 17,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Barrens",
    ["worldBounds"] = { left=2622.92, right=-7510.42, top=1612.50, bottom=-5143.75 },
    ["names"] = { ["enUS"] = "The Barrens", ["esES"] = "Los Baldíos", ["ptBR"] = "Os Barrens", ["zhCN"] = "贫瘠之地" },
  }
end

-- DBC WMA ID=13  MapID=1  'Kalimdor'
if not MTH_DS_Zones[0] then
  MTH_DS_Zones[0] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 0,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Kalimdor",
    ["worldBounds"] = { left=17066.60, right=-19733.21, top=12799.90, bottom=-11733.30 },
    ["names"] = { ["enUS"] = "Kalimdor" },
  }
end

-- DBC WMA ID=14  MapID=0  'Azeroth'
if not MTH_DS_Zones[0] then
  MTH_DS_Zones[0] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 0,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Azeroth",
    ["worldBounds"] = { left=16000.00, right=-19199.90, top=7466.60, bottom=-16000.00 },
    ["names"] = { ["enUS"] = "Azeroth" },
  }
end

-- DBC WMA ID=15  MapID=0  'Alterac'
if not MTH_DS_Zones[36] then
  MTH_DS_Zones[36] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 36,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Alterac",
    ["worldBounds"] = { left=783.33, right=-2016.67, top=1500.00, bottom=-366.67 },
    ["names"] = { ["enUS"] = "Alterac Mountains", ["esES"] = "Montañas de Alterac", ["ptBR"] = "Montanhas de Alterac", ["zhCN"] = "奥特兰克山脉" },
  }
end

-- DBC WMA ID=16  MapID=0  'Arathi'
if not MTH_DS_Zones[45] then
  MTH_DS_Zones[45] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 45,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Arathi",
    ["worldBounds"] = { left=-866.67, right=-4466.67, top=-133.33, bottom=-2533.33 },
    ["names"] = { ["enUS"] = "Arathi Highlands", ["esES"] = "Tierras Altas de Arathi", ["ptBR"] = "Planalto Arathi", ["zhCN"] = "阿拉希高地" },
  }
end

-- DBC WMA ID=17  MapID=0  'Badlands'
if not MTH_DS_Zones[3] then
  MTH_DS_Zones[3] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 3,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Badlands",
    ["worldBounds"] = { left=-2079.17, right=-4566.67, top=-5889.58, bottom=-7547.92 },
    ["names"] = { ["enUS"] = "Badlands", ["esES"] = "Tierras Inhóspitas", ["ptBR"] = "Ermos", ["zhCN"] = "荒芜之地" },
  }
end

-- DBC WMA ID=19  MapID=0  'BlastedLands'
if not MTH_DS_Zones[4] then
  MTH_DS_Zones[4] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 4,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "BlastedLands",
    ["worldBounds"] = { left=-1241.67, right=-4591.67, top=-10566.67, bottom=-12800.00 },
    ["names"] = { ["enUS"] = "Blasted Lands", ["esES"] = "Tierras Devastadas", ["ptBR"] = "Terras Devastadas", ["zhCN"] = "诅咒之地" },
  }
end

-- DBC WMA ID=20  MapID=0  'Tirisfal'
if not MTH_DS_Zones[85] then
  MTH_DS_Zones[85] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 85,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Tirisfal",
    ["worldBounds"] = { left=3033.33, right=-1485.42, top=3837.50, bottom=825.00 },
    ["names"] = { ["enUS"] = "Tirisfal Glades", ["esES"] = "Claros de Tirisfal", ["ptBR"] = "Os Bosques de Tirisfal", ["zhCN"] = "提瑞斯法林地" },
  }
end

-- DBC WMA ID=21  MapID=0  'Silverpine'
if not MTH_DS_Zones[130] then
  MTH_DS_Zones[130] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 130,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Silverpine",
    ["worldBounds"] = { left=3450.00, right=-750.00, top=1666.67, bottom=-1133.33 },
    ["names"] = { ["enUS"] = "Silverpine Forest", ["esES"] = "Bosque de Argénteos", ["ptBR"] = "Floresta Silverpine", ["zhCN"] = "银松森林" },
  }
end

-- DBC WMA ID=22  MapID=0  'WesternPlaguelands'
if not MTH_DS_Zones[28] then
  MTH_DS_Zones[28] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 28,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "WesternPlaguelands",
    ["worldBounds"] = { left=416.67, right=-3883.33, top=3366.67, bottom=500.00 },
    ["names"] = { ["enUS"] = "Western Plaguelands", ["esES"] = "Tierras de la Peste del Oeste", ["ptBR"] = "Plaguelands Ocidentais", ["zhCN"] = "西瘟疫之地" },
  }
end

-- DBC WMA ID=23  MapID=0  'EasternPlaguelands'
if not MTH_DS_Zones[139] then
  MTH_DS_Zones[139] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 139,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "EasternPlaguelands",
    ["worldBounds"] = { left=-2185.42, right=-6056.25, top=3800.00, bottom=1218.75 },
    ["names"] = { ["enUS"] = "Eastern Plaguelands", ["esES"] = "Tierras de la Peste del Este", ["ptBR"] = "Terras Pestilentas Orientais", ["zhCN"] = "东瘟疫之地" },
  }
end

-- DBC WMA ID=24  MapID=0  'Hilsbrad'
if not MTH_DS_Zones[267] then
  MTH_DS_Zones[267] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 267,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Hilsbrad",
    ["worldBounds"] = { left=1066.67, right=-2133.33, top=400.00, bottom=-1733.33 },
    ["names"] = { ["enUS"] = "Hillsbrad Foothills", ["esES"] = "Laderas de Trabalomas", ["ptBR"] = "Contrafortes de Eira dos Montes", ["zhCN"] = "希尔斯布莱德丘陵" },
  }
end

-- DBC WMA ID=26  MapID=0  'Hinterlands'
if not MTH_DS_Zones[47] then
  MTH_DS_Zones[47] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 47,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Hinterlands",
    ["worldBounds"] = { left=-1575.00, right=-5425.00, top=1466.67, bottom=-1100.00 },
    ["names"] = { ["enUS"] = "The Hinterlands", ["esES"] = "Tierras del Interior", ["ptBR"] = "As Terras Interiores", ["zhCN"] = "辛特兰" },
  }
end

-- DBC WMA ID=27  MapID=0  'DunMorogh'
if not MTH_DS_Zones[1] then
  MTH_DS_Zones[1] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 1,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "DunMorogh",
    ["worldBounds"] = { left=1802.08, right=-3122.92, top=-3877.08, bottom=-7160.42 },
    ["names"] = { ["enUS"] = "Dun Morogh", ["esES"] = "Dun Morogh", ["ptBR"] = "Dun Morogh", ["zhCN"] = "丹莫罗" },
  }
end

-- DBC WMA ID=28  MapID=0  'SearingGorge'
if not MTH_DS_Zones[51] then
  MTH_DS_Zones[51] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 51,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "SearingGorge",
    ["worldBounds"] = { left=-322.92, right=-2554.17, top=-6100.00, bottom=-7587.50 },
    ["names"] = { ["enUS"] = "Searing Gorge", ["esES"] = "La Garganta de Fuego", ["ptBR"] = "Desfiladeiro Searing", ["zhCN"] = "灼热峡谷" },
  }
end

-- DBC WMA ID=29  MapID=0  'BurningSteppes'
if not MTH_DS_Zones[46] then
  MTH_DS_Zones[46] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 46,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "BurningSteppes",
    ["worldBounds"] = { left=-266.67, right=-3195.83, top=-7031.25, bottom=-8983.33 },
    ["names"] = { ["enUS"] = "Burning Steppes", ["esES"] = "Las Estepas Ardientes", ["ptBR"] = "Estepes Ardentes", ["zhCN"] = "燃烧平原" },
  }
end

-- DBC WMA ID=30  MapID=0  'Elwynn'
if not MTH_DS_Zones[12] then
  MTH_DS_Zones[12] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 12,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Elwynn",
    ["worldBounds"] = { left=1535.42, right=-1935.42, top=-7939.58, bottom=-10254.17 },
    ["names"] = { ["enUS"] = "Elwynn Forest", ["esES"] = "Bosque de Elwynn", ["ptBR"] = "Floresta de Elwynn", ["zhCN"] = "艾尔文森林" },
  }
end

-- DBC WMA ID=32  MapID=0  'DeadwindPass'
if not MTH_DS_Zones[41] then
  MTH_DS_Zones[41] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 41,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "DeadwindPass",
    ["worldBounds"] = { left=-833.33, right=-3333.33, top=-9866.67, bottom=-11533.33 },
    ["names"] = { ["enUS"] = "Deadwind Pass", ["esES"] = "Paso de la Muerte", ["ptBR"] = "Desfiladeiro da Morte", ["zhCN"] = "逆风小径" },
  }
end

-- DBC WMA ID=34  MapID=0  'Duskwood'
if not MTH_DS_Zones[10] then
  MTH_DS_Zones[10] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 10,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Duskwood",
    ["worldBounds"] = { left=833.33, right=-1866.67, top=-9716.67, bottom=-11516.67 },
    ["names"] = { ["enUS"] = "Duskwood", ["esES"] = "Bosque del Ocaso", ["ptBR"] = "Floresta do Crepúsculo", ["zhCN"] = "暮色森林" },
  }
end

-- DBC WMA ID=35  MapID=0  'LochModan'
if not MTH_DS_Zones[38] then
  MTH_DS_Zones[38] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 38,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "LochModan",
    ["worldBounds"] = { left=-1993.75, right=-4752.08, top=-4487.50, bottom=-6327.08 },
    ["names"] = { ["enUS"] = "Loch Modan", ["esES"] = "Loch Modan", ["ptBR"] = "Loch Modan", ["zhCN"] = "洛克莫丹" },
  }
end

-- DBC WMA ID=36  MapID=0  'Redridge'
if not MTH_DS_Zones[44] then
  MTH_DS_Zones[44] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 44,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Redridge",
    ["worldBounds"] = { left=-1570.83, right=-3741.67, top=-8575.00, bottom=-10022.92 },
    ["names"] = { ["enUS"] = "Redridge Mountains", ["esES"] = "Montañas Crestagrana", ["ptBR"] = "Montanhas Redridge", ["zhCN"] = "赤脊山" },
  }
end

-- DBC WMA ID=37  MapID=0  'Stranglethorn'
if not MTH_DS_Zones[33] then
  MTH_DS_Zones[33] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 33,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Stranglethorn",
    ["worldBounds"] = { left=2220.83, right=-4160.42, top=-11168.75, bottom=-15422.92 },
    ["names"] = { ["enUS"] = "Stranglethorn Vale", ["esES"] = "Vega de Tuercespina", ["ptBR"] = "Vale Stranglethorn", ["zhCN"] = "荆棘谷" },
  }
end

-- DBC WMA ID=38  MapID=0  'SwampOfSorrows'
if not MTH_DS_Zones[8] then
  MTH_DS_Zones[8] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 8,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "SwampOfSorrows",
    ["worldBounds"] = { left=-2222.92, right=-4516.67, top=-9620.83, bottom=-11150.00 },
    ["names"] = { ["enUS"] = "Swamp of Sorrows", ["esES"] = "Pantano de las Penas", ["ptBR"] = "Pantano das Tristezas", ["zhCN"] = "悲伤沼泽" },
  }
end

-- DBC WMA ID=39  MapID=0  'Westfall'
if not MTH_DS_Zones[40] then
  MTH_DS_Zones[40] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 40,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Westfall",
    ["worldBounds"] = { left=3016.67, right=-483.33, top=-9400.00, bottom=-11733.33 },
    ["names"] = { ["enUS"] = "Westfall", ["esES"] = "Páramos del Poniente", ["ptBR"] = "Westfall", ["zhCN"] = "西部荒野" },
  }
end

-- DBC WMA ID=40  MapID=0  'Wetlands'
if not MTH_DS_Zones[11] then
  MTH_DS_Zones[11] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 11,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Wetlands",
    ["worldBounds"] = { left=-389.58, right=-4525.00, top=-2147.92, bottom=-4904.17 },
    ["names"] = { ["enUS"] = "Wetlands", ["esES"] = "Los Humedales", ["ptBR"] = "Pântanos", ["zhCN"] = "湿地" },
  }
end

-- DBC WMA ID=41  MapID=1  'Teldrassil'
if not MTH_DS_Zones[141] then
  MTH_DS_Zones[141] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 141,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Teldrassil",
    ["worldBounds"] = { left=3814.58, right=-1277.08, top=11831.25, bottom=8437.50 },
    ["names"] = { ["enUS"] = "Teldrassil", ["esES"] = "Teldrassil", ["ptBR"] = "Teldrassil", ["zhCN"] = "泰达希尔" },
  }
end

-- DBC WMA ID=42  MapID=1  'Darkshore'
if not MTH_DS_Zones[148] then
  MTH_DS_Zones[148] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 148,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Darkshore",
    ["worldBounds"] = { left=2941.67, right=-3608.33, top=8333.33, bottom=3966.67 },
    ["names"] = { ["enUS"] = "Darkshore", ["esES"] = "Costa Oscura", ["ptBR"] = "Costa Negra", ["zhCN"] = "黑海岸" },
  }
end

-- DBC WMA ID=43  MapID=1  'Ashenvale'
if not MTH_DS_Zones[331] then
  MTH_DS_Zones[331] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 331,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Ashenvale",
    ["worldBounds"] = { left=1700.00, right=-4066.67, top=4672.92, bottom=829.17 },
    ["names"] = { ["enUS"] = "Ashenvale", ["esES"] = "Vallefresno", ["ptBR"] = "Vale das Cinzas", ["zhCN"] = "灰谷" },
  }
end

-- DBC WMA ID=61  MapID=1  'ThousandNeedles'
if not MTH_DS_Zones[400] then
  MTH_DS_Zones[400] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 400,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "ThousandNeedles",
    ["worldBounds"] = { left=-433.33, right=-4833.33, top=-3966.67, bottom=-6900.00 },
    ["names"] = { ["enUS"] = "Thousand Needles", ["esES"] = "Las Mil Agujas", ["ptBR"] = "As Mil Agulhas", ["zhCN"] = "千针石林" },
  }
end

-- DBC WMA ID=81  MapID=1  'StonetalonMountains'
if not MTH_DS_Zones[406] then
  MTH_DS_Zones[406] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 406,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "StonetalonMountains",
    ["worldBounds"] = { left=3245.83, right=-1637.50, top=2916.67, bottom=-339.58 },
    ["names"] = { ["enUS"] = "Stonetalon Mountains", ["esES"] = "Montañas de Colina Roca", ["ptBR"] = "Montanhas Stonetalon", ["zhCN"] = "石爪山脉" },
  }
end

-- DBC WMA ID=101  MapID=1  'Desolace'
if not MTH_DS_Zones[405] then
  MTH_DS_Zones[405] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 405,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Desolace",
    ["worldBounds"] = { left=4233.33, right=-262.50, top=452.08, bottom=-2545.83 },
    ["names"] = { ["enUS"] = "Desolace", ["esES"] = "Desolace", ["ptBR"] = "Desolação", ["zhCN"] = "凄凉之地" },
  }
end

-- DBC WMA ID=121  MapID=1  'Feralas'
if not MTH_DS_Zones[357] then
  MTH_DS_Zones[357] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 357,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Feralas",
    ["worldBounds"] = { left=5441.67, right=-1508.33, top=-2366.67, bottom=-7000.00 },
    ["names"] = { ["enUS"] = "Feralas", ["esES"] = "Feralas", ["ptBR"] = "Feralas", ["zhCN"] = "菲拉斯" },
  }
end

-- DBC WMA ID=141  MapID=1  'Dustwallow'
if not MTH_DS_Zones[15] then
  MTH_DS_Zones[15] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 15,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Dustwallow",
    ["worldBounds"] = { left=-975.00, right=-6225.00, top=-2033.33, bottom=-5533.33 },
    ["names"] = { ["enUS"] = "Dustwallow Marsh", ["esES"] = "Marjal Revolcafango", ["ptBR"] = "Pântano Vadeante", ["zhCN"] = "尘泥沼泽" },
  }
end

-- DBC WMA ID=161  MapID=1  'Tanaris'
if not MTH_DS_Zones[440] then
  MTH_DS_Zones[440] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 440,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Tanaris",
    ["worldBounds"] = { left=-218.75, right=-7118.75, top=-5875.00, bottom=-10475.00 },
    ["names"] = { ["enUS"] = "Tanaris", ["esES"] = "Tanaris", ["ptBR"] = "Tanaris", ["zhCN"] = "塔纳利斯" },
  }
end

-- DBC WMA ID=181  MapID=1  'Aszhara'
if not MTH_DS_Zones[16] then
  MTH_DS_Zones[16] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 16,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Aszhara",
    ["worldBounds"] = { left=-3277.08, right=-8347.92, top=5341.67, bottom=1960.42 },
    ["names"] = { ["enUS"] = "Azshara", ["esES"] = "Azshara", ["ptBR"] = "Azshara", ["zhCN"] = "艾萨拉" },
  }
end

-- DBC WMA ID=182  MapID=1  'Felwood'
if not MTH_DS_Zones[361] then
  MTH_DS_Zones[361] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 361,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Felwood",
    ["worldBounds"] = { left=1641.67, right=-4108.33, top=7133.33, bottom=3300.00 },
    ["names"] = { ["enUS"] = "Felwood", ["esES"] = "Frondavil", ["ptBR"] = "Selva Maleva", ["zhCN"] = "费伍德森林" },
  }
end

-- DBC WMA ID=201  MapID=1  'UngoroCrater'
if not MTH_DS_Zones[490] then
  MTH_DS_Zones[490] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 490,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "UngoroCrater",
    ["worldBounds"] = { left=533.33, right=-3166.67, top=-5966.67, bottom=-8433.33 },
    ["names"] = { ["enUS"] = "Un'Goro Crater", ["esES"] = "Crater Un'Goro", ["ptBR"] = "Cratera Un'Goro", ["zhCN"] = "安戈洛环形山" },
  }
end

-- DBC WMA ID=241  MapID=1  'Moonglade'
if not MTH_DS_Zones[493] then
  MTH_DS_Zones[493] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 493,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Moonglade",
    ["worldBounds"] = { left=-1381.25, right=-3689.58, top=8491.67, bottom=6952.08 },
    ["names"] = { ["enUS"] = "Moonglade", ["esES"] = "Claro de la Luna", ["ptBR"] = "Moonglade", ["zhCN"] = "月光林地" },
  }
end

-- DBC WMA ID=261  MapID=1  'Silithus'
if not MTH_DS_Zones[1377] then
  MTH_DS_Zones[1377] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 1377,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Silithus",
    ["worldBounds"] = { left=2537.50, right=-945.83, top=-5958.33, bottom=-8281.25 },
    ["names"] = { ["enUS"] = "Silithus", ["esES"] = "Silithus", ["ptBR"] = "Silithus", ["zhCN"] = "希利苏斯" },
  }
end

-- DBC WMA ID=281  MapID=1  'Winterspring'
if not MTH_DS_Zones[618] then
  MTH_DS_Zones[618] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 618,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Winterspring",
    ["worldBounds"] = { left=-316.67, right=-7416.67, top=8533.33, bottom=3800.00 },
    ["names"] = { ["enUS"] = "Winterspring", ["esES"] = "Winterspring", ["ptBR"] = "Inverno", ["zhCN"] = "冬泉谷" },
  }
end

-- DBC WMA ID=341  MapID=0  'Ironforge'
if not MTH_DS_Zones[1537] then
  MTH_DS_Zones[1537] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 1537,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Ironforge",
    ["worldBounds"] = { left=-713.59, right=-1504.22, top=-4569.24, bottom=-5096.85 },
    ["names"] = { ["enUS"] = "Ironforge", ["esES"] = "Forjaz", ["ptBR"] = "Altaforja", ["zhCN"] = "铁炉堡" },
  }
end

-- DBC WMA ID=401  MapID=30  'AlteracValley'
if not MTH_DS_Zones[2597] then
  MTH_DS_Zones[2597] = {
    ["continent"] = 30,
    ["parent"]    = 30,
    ["dbcAreaId"] = 2597,
    ["dbcMapId"]  = 30,
    ["dbcName"]   = "AlteracValley",
    ["worldBounds"] = { left=1781.25, right=-2456.25, top=1085.42, bottom=-1739.58 },
    ["names"] = { ["enUS"] = "Alterac Valley", ["esES"] = "Valle de Alterac", ["ptBR"] = "Vale Alterac", ["zhCN"] = "奥特兰克山谷" },
  }
end

-- DBC WMA ID=443  MapID=489  'WarsongGulch'
if not MTH_DS_Zones[3277] then
  MTH_DS_Zones[3277] = {
    ["continent"] = 489,
    ["parent"]    = 489,
    ["dbcAreaId"] = 3277,
    ["dbcMapId"]  = 489,
    ["dbcName"]   = "WarsongGulch",
    ["worldBounds"] = { left=2041.67, right=895.83, top=1627.08, bottom=862.50 },
    ["names"] = { ["enUS"] = "Warsong Gulch", ["esES"] = "Garganta de Warsong", ["ptBR"] = "Garganta Grito de Guerra", ["zhCN"] = "战歌峡谷" },
  }
end

-- DBC WMA ID=461  MapID=529  'ArathiBasin'
if not MTH_DS_Zones[3358] then
  MTH_DS_Zones[3358] = {
    ["continent"] = 529,
    ["parent"]    = 529,
    ["dbcAreaId"] = 3358,
    ["dbcMapId"]  = 529,
    ["dbcName"]   = "ArathiBasin",
    ["worldBounds"] = { left=1858.33, right=102.08, top=1508.33, bottom=337.50 },
    ["names"] = { ["enUS"] = "Arathi Basin", ["esES"] = "Cuenca de Arathi", ["ptBR"] = "Bacia Arathi", ["zhCN"] = "阿拉希盆地" },
  }
end

-- DBC WMA ID=500  MapID=1  'GMIsland'
if not MTH_DS_Zones[876] then
  MTH_DS_Zones[876] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 876,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "GMIsland",
    ["worldBounds"] = { left=16748.00, right=15920.00, top=16525.00, bottom=15984.00 },
    ["names"] = { ["enUS"] = "GM Island", ["esES"] = "Isla GM", ["ptBR"] = "Ilha GM", ["zhCN"] = "GM岛" },
  }
end

-- DBC WMA ID=501  MapID=1  'Hyjal'
if not MTH_DS_Zones[616] then
  MTH_DS_Zones[616] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 616,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Hyjal",
    ["worldBounds"] = { left=-1080.00, right=-4286.00, top=6125.00, bottom=3983.00 },
    ["names"] = { ["enUS"] = "Hyjal", ["esES"] = "Hyjal", ["ptBR"] = "Hyjal", ["zhCN"] = "海加尔山" },
  }
end

-- DBC WMA ID=502  MapID=0  'ScarletEnclave'
if not MTH_DS_Zones[4012] then
  MTH_DS_Zones[4012] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 4012,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "ScarletEnclave",
    ["worldBounds"] = { left=-4050.00, right=-7209.00, top=3087.00, bottom=979.00 },
    ["names"] = { ["enUS"] = "Scarlet Enclave", ["esES"] = "Enclave Escarlata", ["ptBR"] = "Enclave Scarlet", ["zhCN"] = "东瘟疫之地：血色领地" },
  }
end

-- DBC WMA ID=503  MapID=27  'Sunnyglade'
if not MTH_DS_Zones[5023] then
  MTH_DS_Zones[5023] = {
    ["continent"] = 27,
    ["parent"]    = 27,
    ["dbcAreaId"] = 5023,
    ["dbcMapId"]  = 27,
    ["dbcName"]   = "Sunnyglade",
    ["worldBounds"] = { left=719.47, right=-269.16, top=2000.77, bottom=607.60 },
    ["names"] = { ["enUS"] = "Sunnyglade Valley", ["esES"] = "Valle Claro Sol", ["ptBR"] = "Vale Sunnyglade", ["zhCN"] = "阳光林地山谷" },
  }
end

-- DBC WMA ID=504  MapID=0  'Lapidis'
if not MTH_DS_Zones[409] then
  MTH_DS_Zones[409] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 409,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Lapidis",
    ["worldBounds"] = { left=4933.33, right=2031.88, top=-11043.48, bottom=-12959.42 },
    ["names"] = { ["enUS"] = "Lapidis Isle", ["esES"] = "Isla Lapidis", ["ptBR"] = "Isla Lapidis", ["zhCN"] = "拉匹迪斯之岛" },
  }
end

-- DBC WMA ID=505  MapID=0  'Gillijim'
if not MTH_DS_Zones[408] then
  MTH_DS_Zones[408] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 408,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Gillijim",
    ["worldBounds"] = { left=4436.22, right=1344.12, top=-12528.71, bottom=-14575.72 },
    ["names"] = { ["enUS"] = "Gillijim's Isle", ["esES"] = "Isla de Gillijim", ["ptBR"] = "Ilha de Gillijim", ["zhCN"] = "吉利吉姆之岛" },
  }
end

-- DBC WMA ID=506  MapID=31  'AlteracValleyClassic'
if not MTH_DS_Zones[2597] then
  MTH_DS_Zones[2597] = {
    ["continent"] = 31,
    ["parent"]    = 31,
    ["dbcAreaId"] = 2597,
    ["dbcMapId"]  = 31,
    ["dbcName"]   = "AlteracValleyClassic",
    ["worldBounds"] = { left=1781.25, right=-2456.25, top=1085.42, bottom=-1739.58 },
    ["names"] = { ["enUS"] = "Alterac Valley", ["esES"] = "Valle de Alterac", ["ptBR"] = "Vale Alterac", ["zhCN"] = "奥特兰克山谷" },
  }
end

-- DBC WMA ID=507  MapID=1  'TelAbim'
if not MTH_DS_Zones[5121] then
  MTH_DS_Zones[5121] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 5121,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "TelAbim",
    ["worldBounds"] = { left=-5179.00, right=-8406.00, top=-7184.00, bottom=-9371.00 },
    ["names"] = { ["enUS"] = "Tel'Abim", ["esES"] = "Tel'Abim", ["ptBR"] = "Tel'Abim", ["zhCN"] = "泰拉比姆" },
  }
end

-- DBC WMA ID=510  MapID=0  'Gilneas'
if not MTH_DS_Zones[5179] then
  MTH_DS_Zones[5179] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 5179,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "Gilneas",
    ["worldBounds"] = { left=3253.00, right=-413.00, top=-359.00, bottom=-2801.00 },
    ["names"] = { ["enUS"] = "Gilneas", ["esES"] = "Gilneas", ["ptBR"] = "Gilneas", ["zhCN"] = "吉尔尼斯" },
  }
end

-- DBC WMA ID=511  MapID=1  'Icepoint'
if not MTH_DS_Zones[5024] then
  MTH_DS_Zones[5024] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 5024,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "Icepoint",
    ["worldBounds"] = { left=-5595.00, right=-7203.00, top=14405.00, bottom=13330.00 },
    ["names"] = { ["enUS"] = "Icepoint Rock", ["esES"] = "Roca Punto de Hielo", ["ptBR"] = "Roca Punto de Hielo", ["zhCN"] = "冰点岩" },
  }
end

-- DBC WMA ID=512  MapID=1  'BlackstoneIsland'
if not MTH_DS_Zones[5536] then
  MTH_DS_Zones[5536] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 5536,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "BlackstoneIsland",
    ["worldBounds"] = { left=-6274.00, right=-8746.00, top=799.00, bottom=-866.00 },
    ["names"] = { ["enUS"] = "Blackstone Island", ["esES"] = "Isla Piedra Negra", ["ptBR"] = "Ilha Negrito", ["zhCN"] = "黑石岛" },
  }
end

-- DBC WMA ID=513  MapID=0  'ThalassianHighlands'
if not MTH_DS_Zones[5225] then
  MTH_DS_Zones[5225] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 5225,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "ThalassianHighlands",
    ["worldBounds"] = { left=-1005.00, right=-4087.00, top=4952.00, bottom=2891.00 },
    ["names"] = { ["enUS"] = "Thalassian Highlands", ["esES"] = "Tierras Altas Thalassianas", ["ptBR"] = "Terras Altas Thalassianas", ["zhCN"] = "萨拉斯高地" },
  }
end

-- DBC WMA ID=514  MapID=0  'DeadminesEntrance'
if not MTH_DS_Zones[1581] then
  MTH_DS_Zones[1581] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 1581,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "DeadminesEntrance",
    ["worldBounds"] = { left=1793.18, right=1343.29, top=-11054.94, bottom=-11354.86 },
    ["names"] = { ["enUS"] = "The Deadmines", ["esES"] = "Las Minas de la Muerte", ["ptBR"] = "As Minas Mortas", ["zhCN"] = "死亡矿井" },
  }
end

-- DBC WMA ID=516  MapID=1  'WailingCavernsEntrance'
if not MTH_DS_Zones[718] then
  MTH_DS_Zones[718] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 718,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "WailingCavernsEntrance",
    ["worldBounds"] = { left=-1900.87, right=-2473.65, top=-488.64, bottom=-870.49 },
    ["names"] = { ["enUS"] = "Wailing Caverns", ["esES"] = "Cuevas de los Lamentos", ["ptBR"] = "Cavernas Uivantes", ["zhCN"] = "哀嚎洞穴" },
  }
end

-- DBC WMA ID=517  MapID=1  'MaraudonEntrance'
if not MTH_DS_Zones[2100] then
  MTH_DS_Zones[2100] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 2100,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "MaraudonEntrance",
    ["worldBounds"] = { left=3208.00, right=2384.00, top=-1096.00, bottom=-1646.00 },
    ["names"] = { ["enUS"] = "Maraudon", ["esES"] = "Maraudon", ["ptBR"] = "Maraudon", ["zhCN"] = "玛拉顿" },
  }
end

-- DBC WMA ID=518  MapID=0  'GnomereganEntrance'
if not MTH_DS_Zones[721] then
  MTH_DS_Zones[721] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 721,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "GnomereganEntrance",
    ["worldBounds"] = { left=1027.64, right=456.45, top=-4806.32, bottom=-5185.46 },
    ["names"] = { ["enUS"] = "Gnomeregan", ["esES"] = "Gnomeregan", ["ptBR"] = "Gnomeregan", ["zhCN"] = "诺莫瑞根" },
  }
end

-- DBC WMA ID=519  MapID=0  'BlackrockMountain'
if not MTH_DS_Zones[25] then
  MTH_DS_Zones[25] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 25,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "BlackrockMountain",
    ["worldBounds"] = { left=-760.94, right=-1472.50, top=-7327.82, bottom=-7796.50 },
    ["names"] = { ["enUS"] = "Blackrock Mountain", ["esES"] = "Montaña Roca Negra", ["ptBR"] = "Montanha Rocha Negra", ["zhCN"] = "黑石山" },
  }
end

-- DBC WMA ID=520  MapID=0  'ScarletMonasteryEntrance'
if not MTH_DS_Zones[796] then
  MTH_DS_Zones[796] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 796,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "ScarletMonasteryEntrance",
    ["worldBounds"] = { left=-659.96, right=-863.62, top=2947.37, bottom=2812.33 },
    ["names"] = { ["enUS"] = "Scarlet Monastery", ["esES"] = "Monasterio Escarlata", ["ptBR"] = "Monastério Scarlet", ["zhCN"] = "血色修道院" },
  }
end

-- DBC WMA ID=521  MapID=0  'UldamanEntrance'
if not MTH_DS_Zones[1337] then
  MTH_DS_Zones[1337] = {
    ["continent"] = 0,
    ["parent"]    = 0,
    ["dbcAreaId"] = 1337,
    ["dbcMapId"]  = 0,
    ["dbcName"]   = "UldamanEntrance",
    ["worldBounds"] = { left=-2747.15, right=-3310.46, top=-5953.41, bottom=-6329.51 },
    ["names"] = { ["enUS"] = "Uldaman", ["esES"] = "Uldaman", ["ptBR"] = "Uldaman", ["zhCN"] = "奥达曼" },
  }
end

-- DBC WMA ID=522  MapID=1  'AhnQirajEntrance'
if not MTH_DS_Zones[3478] then
  MTH_DS_Zones[3478] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 3478,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "AhnQirajEntrance",
    ["worldBounds"] = { left=3932.67, right=-206.35, top=-8005.20, bottom=-10951.25 },
    ["names"] = { ["enUS"] = "Gates of Ahn'Qiraj", ["esES"] = "Puertas de Ahn'Qiraj", ["ptBR"] = "Portões de Ahn'Qiraj", ["zhCN"] = "安其拉之门" },
  }
end

-- DBC WMA ID=523  MapID=1  'CavernsOfTime'
if not MTH_DS_Zones[1941] then
  MTH_DS_Zones[1941] = {
    ["continent"] = 1,
    ["parent"]    = 1,
    ["dbcAreaId"] = 1941,
    ["dbcMapId"]  = 1,
    ["dbcName"]   = "CavernsOfTime",
    ["worldBounds"] = { left=-3695.85, right=-5044.09, top=-8023.09, bottom=-8911.18 },
    ["names"] = { ["enUS"] = "Caverns of Time", ["esES"] = "Cavernas del Tiempo", ["ptBR"] = "Cavernas do Tempo", ["zhCN"] = "时光之穴" },
  }
end

-- DBC WMA ID=601  MapID=813  'WinterVeilVale'
if not MTH_DS_Zones[5130] then
  MTH_DS_Zones[5130] = {
    ["continent"] = 813,
    ["parent"]    = 813,
    ["dbcAreaId"] = 5130,
    ["dbcMapId"]  = 813,
    ["dbcName"]   = "WinterVeilVale",
    ["worldBounds"] = { left=1916.00, right=484.00, top=-2332.00, bottom=-3309.00 },
    ["names"] = { ["enUS"] = "Winter Veil Vale", ["esES"] = "Valle del Velo Invernal", ["ptBR"] = "Vale do Véu de Inverno", ["zhCN"] = "冬幕谷" },
  }
end

-- DBC WMA ID=603  MapID=389  'Ragefire'
if not MTH_DS_Zones[2437] then
  MTH_DS_Zones[2437] = {
    ["continent"] = 389,
    ["parent"]    = 389,
    ["dbcAreaId"] = 2437,
    ["dbcMapId"]  = 389,
    ["dbcName"]   = "Ragefire",
    ["worldBounds"] = { left=452.87, right=-285.99, top=39.62, bottom=-452.95 },
    ["names"] = { ["enUS"] = "Ragefire Chasm", ["esES"] = "Sima Ígnea", ["ptBR"] = "Cavernas Ragefire", ["zhCN"] = "怒焰裂谷" },
  }
end

-- DBC WMA ID=605  MapID=209  'ZulFarrak'
if not MTH_DS_Zones[1176] then
  MTH_DS_Zones[1176] = {
    ["continent"] = 209,
    ["parent"]    = 209,
    ["dbcAreaId"] = 1176,
    ["dbcMapId"]  = 209,
    ["dbcName"]   = "ZulFarrak",
    ["worldBounds"] = { left=1625.00, right=241.67, top=2052.08, bottom=1129.17 },
    ["names"] = { ["enUS"] = "Zul'Farrak", ["esES"] = "Zul'Farrak", ["ptBR"] = "Zul'Farrak", ["zhCN"] = "祖尔法拉克" },
  }
end

-- DBC WMA ID=607  MapID=109  'TheTempleOfAtalHakkar'
if not MTH_DS_Zones[1477] then
  MTH_DS_Zones[1477] = {
    ["continent"] = 109,
    ["parent"]    = 109,
    ["dbcAreaId"] = 1477,
    ["dbcMapId"]  = 109,
    ["dbcName"]   = "TheTempleOfAtalHakkar",
    ["worldBounds"] = { left=442.76, right=-252.27, top=-255.17, bottom=-718.52 },
    ["names"] = { ["enUS"] = "The Temple of Atal'Hakkar", ["esES"] = "Templo de Atal'Hakkar", ["ptBR"] = "O Templo de Atal'Hakkar", ["zhCN"] = "阿塔哈卡神庙" },
  }
end

-- DBC WMA ID=609  MapID=48  'BlackFathomDeeps'
if not MTH_DS_Zones[719] then
  MTH_DS_Zones[719] = {
    ["continent"] = 48,
    ["parent"]    = 48,
    ["dbcAreaId"] = 719,
    ["dbcMapId"]  = 48,
    ["dbcName"]   = "BlackFathomDeeps",
    ["worldBounds"] = { left=485.41, right=-736.46, top=-107.91, bottom=-914.33 },
    ["names"] = { ["enUS"] = "Blackfathom Deeps", ["esES"] = "Cavernas de Brazanegra", ["ptBR"] = "Profundezas Negras", ["zhCN"] = "黑暗深渊" },
  }
end

-- DBC WMA ID=611  MapID=34  'TheStockade'
if not MTH_DS_Zones[717] then
  MTH_DS_Zones[717] = {
    ["continent"] = 34,
    ["parent"]    = 34,
    ["dbcAreaId"] = 717,
    ["dbcMapId"]  = 34,
    ["dbcName"]   = "TheStockade",
    ["worldBounds"] = { left=189.82, right=-188.33, top=220.63, bottom=-31.47 },
    ["names"] = { ["enUS"] = "The Stockade", ["esES"] = "La Mazmorras", ["ptBR"] = "A Prisão", ["zhCN"] = "监狱" },
  }
end

-- DBC WMA ID=613  MapID=90  'Gnomeregan'
if not MTH_DS_Zones[721] then
  MTH_DS_Zones[721] = {
    ["continent"] = 90,
    ["parent"]    = 90,
    ["dbcAreaId"] = 721,
    ["dbcMapId"]  = 90,
    ["dbcName"]   = "Gnomeregan",
    ["worldBounds"] = { left=491.90, right=-277.77, top=-180.89, bottom=-694.00 },
    ["names"] = { ["enUS"] = "Gnomeregan", ["esES"] = "Gnomeregan", ["ptBR"] = "Gnomeregan", ["zhCN"] = "诺莫瑞根" },
  }
end

-- DBC WMA ID=615  MapID=70  'Uldaman'
if not MTH_DS_Zones[1337] then
  MTH_DS_Zones[1337] = {
    ["continent"] = 70,
    ["parent"]    = 70,
    ["dbcAreaId"] = 1337,
    ["dbcMapId"]  = 70,
    ["dbcName"]   = "Uldaman",
    ["worldBounds"] = { left=645.12, right=-248.55, top=204.31, bottom=-391.47 },
    ["names"] = { ["enUS"] = "Uldaman", ["esES"] = "Uldaman", ["ptBR"] = "Uldaman", ["zhCN"] = "奥达曼" },
  }
end

-- DBC WMA ID=617  MapID=409  'MoltenCore'
if not MTH_DS_Zones[2717] then
  MTH_DS_Zones[2717] = {
    ["continent"] = 409,
    ["parent"]    = 409,
    ["dbcAreaId"] = 2717,
    ["dbcMapId"]  = 409,
    ["dbcName"]   = "MoltenCore",
    ["worldBounds"] = { left=-130.76, right=-1395.56, top=1303.06, bottom=459.86 },
    ["names"] = { ["enUS"] = "Molten Core", ["esES"] = "Núcleo de Magma", ["ptBR"] = "Núcleo Derretido", ["zhCN"] = "熔火之心" },
  }
end

-- DBC WMA ID=619  MapID=309  'ZulGurub'
if not MTH_DS_Zones[1977] then
  MTH_DS_Zones[1977] = {
    ["continent"] = 309,
    ["parent"]    = 309,
    ["dbcAreaId"] = 1977,
    ["dbcMapId"]  = 309,
    ["dbcName"]   = "ZulGurub",
    ["worldBounds"] = { left=-612.50, right=-2733.33, top=-11225.00, bottom=-12639.58 },
    ["names"] = { ["enUS"] = "Zul'Gurub", ["esES"] = "Zul'Gurub", ["ptBR"] = "Zul'Gurub", ["zhCN"] = "祖尔格拉布" },
  }
end

-- DBC WMA ID=621  MapID=429  'DireMaul'
if not MTH_DS_Zones[2557] then
  MTH_DS_Zones[2557] = {
    ["continent"] = 429,
    ["parent"]    = 429,
    ["dbcAreaId"] = 2557,
    ["dbcMapId"]  = 429,
    ["dbcName"]   = "DireMaul",
    ["worldBounds"] = { left=887.50, right=-387.50, top=1050.00, bottom=200.00 },
    ["names"] = { ["enUS"] = "Dire Maul", ["esES"] = "La Masacre", ["ptBR"] = "Gládio Cruel", ["zhCN"] = "厄运之槌" },
  }
end

-- DBC WMA ID=623  MapID=230  'BlackrockDepths'
if not MTH_DS_Zones[1584] then
  MTH_DS_Zones[1584] = {
    ["continent"] = 230,
    ["parent"]    = 230,
    ["dbcAreaId"] = 1584,
    ["dbcMapId"]  = 230,
    ["dbcName"]   = "BlackrockDepths",
    ["worldBounds"] = { left=522.34, right=-884.72, top=1186.68, bottom=248.64 },
    ["names"] = { ["enUS"] = "Blackrock Depths", ["esES"] = "Profundidades de Roca Negra", ["ptBR"] = "Abismo Rocha Negra", ["zhCN"] = "黑石深渊" },
  }
end

-- DBC WMA ID=625  MapID=509  'RuinsofAhnQiraj'
if not MTH_DS_Zones[3429] then
  MTH_DS_Zones[3429] = {
    ["continent"] = 509,
    ["parent"]    = 509,
    ["dbcAreaId"] = 3429,
    ["dbcMapId"]  = 509,
    ["dbcName"]   = "RuinsofAhnQiraj",
    ["worldBounds"] = { left=3035.42, right=522.92, top=-8233.33, bottom=-9908.33 },
    ["names"] = { ["enUS"] = "Ruins of Ahn'Qiraj", ["esES"] = "Ruinas de Ahn'Qiraj", ["ptBR"] = "Ruínas de Ahn'Qiraj", ["zhCN"] = "安其拉废墟" },
  }
end

-- DBC WMA ID=627  MapID=249  'OnyxiasLair'
if not MTH_DS_Zones[2159] then
  MTH_DS_Zones[2159] = {
    ["continent"] = 249,
    ["parent"]    = 249,
    ["dbcAreaId"] = 2159,
    ["dbcMapId"]  = 249,
    ["dbcName"]   = "OnyxiasLair",
    ["worldBounds"] = { left=111.38, right=-371.73, top=98.25, bottom=-223.83 },
    ["names"] = { ["enUS"] = "Onyxia's Lair", ["esES"] = "Guarida de Onyxia", ["ptBR"] = "Caverna de Onyxia", ["zhCN"] = "奥妮克希亚的巢穴" },
  }
end

-- DBC WMA ID=629  MapID=229  'BlackrockSpire'
if not MTH_DS_Zones[1583] then
  MTH_DS_Zones[1583] = {
    ["continent"] = 229,
    ["parent"]    = 229,
    ["dbcAreaId"] = 1583,
    ["dbcMapId"]  = 229,
    ["dbcName"]   = "BlackrockSpire",
    ["worldBounds"] = { left=10.59, right=-876.25, top=304.40, bottom=-286.83 },
    ["names"] = { ["enUS"] = "Blackrock Spire", ["esES"] = "Cumbre de Roca Negra", ["ptBR"] = "Pico Rocha Negra", ["zhCN"] = "黑石塔" },
  }
end

-- DBC WMA ID=631  MapID=43  'WailingCaverns'
if not MTH_DS_Zones[718] then
  MTH_DS_Zones[718] = {
    ["continent"] = 43,
    ["parent"]    = 43,
    ["dbcAreaId"] = 718,
    ["dbcMapId"]  = 43,
    ["dbcName"]   = "WailingCaverns",
    ["worldBounds"] = { left=790.00, right=-380.00, top=215.00, bottom=-570.00 },
    ["names"] = { ["enUS"] = "Wailing Caverns", ["esES"] = "Cuevas de los Lamentos", ["ptBR"] = "Cavernas Uivantes", ["zhCN"] = "哀嚎洞穴" },
  }
end

-- DBC WMA ID=633  MapID=349  'Maraudon'
if not MTH_DS_Zones[2100] then
  MTH_DS_Zones[2100] = {
    ["continent"] = 349,
    ["parent"]    = 349,
    ["dbcAreaId"] = 2100,
    ["dbcMapId"]  = 349,
    ["dbcName"]   = "Maraudon",
    ["worldBounds"] = { left=485.41, right=-1626.68, top=1199.76, bottom=-211.13 },
    ["names"] = { ["enUS"] = "Maraudon", ["esES"] = "Maraudon", ["ptBR"] = "Maraudon", ["zhCN"] = "玛拉顿" },
  }
end

-- DBC WMA ID=635  MapID=469  'BlackwingLair'
if not MTH_DS_Zones[2677] then
  MTH_DS_Zones[2677] = {
    ["continent"] = 469,
    ["parent"]    = 469,
    ["dbcAreaId"] = 2677,
    ["dbcMapId"]  = 469,
    ["dbcName"]   = "BlackwingLair",
    ["worldBounds"] = { left=-844.62, right=-1344.05, top=-7394.12, bottom=-7727.07 },
    ["names"] = { ["enUS"] = "Blackwing Lair", ["esES"] = "Guarida Alanegra", ["ptBR"] = "Covil Asa Negra", ["zhCN"] = "黑翼之巢" },
  }
end

-- DBC WMA ID=637  MapID=36  'TheDeadmines'
if not MTH_DS_Zones[5138] then
  MTH_DS_Zones[5138] = {
    ["continent"] = 36,
    ["parent"]    = 36,
    ["dbcAreaId"] = 5138,
    ["dbcMapId"]  = 36,
    ["dbcName"]   = "TheDeadmines",
    ["worldBounds"] = { left=-322.94, right=-979.53, top=36.93, bottom=-398.04 },
    ["names"] = { ["enUS"] = "The Deadmines", ["esES"] = "Las Minas de la Muerte", ["ptBR"] = "As Minas Mortas", ["zhCN"] = "死亡矿井" },
  }
end

-- DBC WMA ID=639  MapID=129  'RazorfenDowns'
if not MTH_DS_Zones[722] then
  MTH_DS_Zones[722] = {
    ["continent"] = 129,
    ["parent"]    = 129,
    ["dbcAreaId"] = 722,
    ["dbcMapId"]  = 129,
    ["dbcName"]   = "RazorfenDowns",
    ["worldBounds"] = { left=1279.94, right=570.89, top=2682.55, bottom=2209.85 },
    ["names"] = { ["enUS"] = "Razorfen Downs", ["esES"] = "Tierras Bajas de Rajacieno", ["ptBR"] = "Razorfen Downs", ["zhCN"] = "剃刀高地" },
  }
end

-- DBC WMA ID=641  MapID=47  'RazorfenKraul'
if not MTH_DS_Zones[491] then
  MTH_DS_Zones[491] = {
    ["continent"] = 47,
    ["parent"]    = 47,
    ["dbcAreaId"] = 491,
    ["dbcMapId"]  = 47,
    ["dbcName"]   = "RazorfenKraul",
    ["worldBounds"] = { left=2058.92, right=1322.47, top=2349.64, bottom=1858.68 },
    ["names"] = { ["enUS"] = "Razorfen Kraul", ["esES"] = "Madriguera de Rajacieno", ["ptBR"] = "Razorfen Kraul", ["zhCN"] = "剃刀沼泽" },
  }
end

-- DBC WMA ID=643  MapID=189  'ScarletMonastery'
if not MTH_DS_Zones[5136] then
  MTH_DS_Zones[5136] = {
    ["continent"] = 189,
    ["parent"]    = 189,
    ["dbcAreaId"] = 5136,
    ["dbcMapId"]  = 189,
    ["dbcName"]   = "ScarletMonastery",
    ["worldBounds"] = { left=1567.97, right=947.99, top=2030.18, bottom=1616.86 },
    ["names"] = { ["enUS"] = "Scarlet Monastery Graveyard", ["esES"] = "Cementerio Monasterio Escarlata", ["ptBR"] = "Cemitério do Monastério Escarlate", ["zhCN"] = "血色修道院-墓地" },
  }
end

-- DBC WMA ID=644  MapID=189  'ScarletMonastery2f'
if not MTH_DS_Zones[5135] then
  MTH_DS_Zones[5135] = {
    ["continent"] = 189,
    ["parent"]    = 189,
    ["dbcAreaId"] = 5135,
    ["dbcMapId"]  = 189,
    ["dbcName"]   = "ScarletMonastery2f",
    ["worldBounds"] = { left=-162.27, right=-482.46, top=307.37, bottom=93.91 },
    ["names"] = { ["enUS"] = "Scarlet Monastery Library", ["esES"] = "Biblioteca Monasterio Escarlata", ["ptBR"] = "Biblioteca do Monastério Escarlate", ["zhCN"] = "血色修道院-图书馆" },
  }
end

-- DBC WMA ID=645  MapID=189  'ScarletMonastery3f'
if not MTH_DS_Zones[5153] then
  MTH_DS_Zones[5153] = {
    ["continent"] = 189,
    ["parent"]    = 189,
    ["dbcAreaId"] = 5153,
    ["dbcMapId"]  = 189,
    ["dbcName"]   = "ScarletMonastery3f",
    ["worldBounds"] = { left=50.27, right=-562.42, top=2009.10, bottom=1600.64 },
    ["names"] = { ["enUS"] = "Scarlet Monastery Armory", ["esES"] = "Armería Monasterio Escarlata", ["ptBR"] = "Arsenal do Monastério Escarlate", ["zhCN"] = "血色修道院-军械库" },
  }
end

-- DBC WMA ID=646  MapID=189  'ScarletMonastery4f'
if not MTH_DS_Zones[5163] then
  MTH_DS_Zones[5163] = {
    ["continent"] = 189,
    ["parent"]    = 189,
    ["dbcAreaId"] = 5163,
    ["dbcMapId"]  = 189,
    ["dbcName"]   = "ScarletMonastery4f",
    ["worldBounds"] = { left=1743.99, right=1040.69, top=1281.29, bottom=812.42 },
    ["names"] = { ["enUS"] = "Scarlet Monastery Cathedral", ["esES"] = "Catedral Monasterio Escarlata", ["ptBR"] = "Catedral do Monastério Escarlate", ["zhCN"] = "血色修道院-大教堂" },
  }
end

-- DBC WMA ID=648  MapID=289  'Scholomance'
if not MTH_DS_Zones[2057] then
  MTH_DS_Zones[2057] = {
    ["continent"] = 289,
    ["parent"]    = 289,
    ["dbcAreaId"] = 2057,
    ["dbcMapId"]  = 289,
    ["dbcName"]   = "Scholomance",
    ["worldBounds"] = { left=251.41, right=-68.64, top=317.70, bottom=104.33 },
    ["names"] = { ["enUS"] = "Scholomance", ["esES"] = "Scholomance", ["ptBR"] = "Scholomance", ["zhCN"] = "通灵学院" },
  }
end

-- DBC WMA ID=650  MapID=33  'ShadowfangKeep'
if not MTH_DS_Zones[209] then
  MTH_DS_Zones[209] = {
    ["continent"] = 33,
    ["parent"]    = 33,
    ["dbcAreaId"] = 209,
    ["dbcMapId"]  = 33,
    ["dbcName"]   = "ShadowfangKeep",
    ["worldBounds"] = { left=2436.00, right=2055.00, top=-61.00, bottom=-315.00 },
    ["names"] = { ["enUS"] = "Shadowfang Keep", ["esES"] = "Fortaleza Colmillo Oscuro", ["ptBR"] = "Fortaleza Shadowfang", ["zhCN"] = "影牙城堡" },
  }
end

-- DBC WMA ID=652  MapID=329  'Stratholme'
if not MTH_DS_Zones[2017] then
  MTH_DS_Zones[2017] = {
    ["continent"] = 329,
    ["parent"]    = 329,
    ["dbcAreaId"] = 2017,
    ["dbcMapId"]  = 329,
    ["dbcName"]   = "Stratholme",
    ["worldBounds"] = { left=-2639.83, right=-3825.18, top=4163.90, bottom=3374.04 },
    ["names"] = { ["enUS"] = "Stratholme", ["esES"] = "Stratholme", ["ptBR"] = "Stratholme", ["zhCN"] = "斯坦索姆" },
  }
end

-- DBC WMA ID=654  MapID=531  'AhnQiraj'
if not MTH_DS_Zones[3428] then
  MTH_DS_Zones[3428] = {
    ["continent"] = 531,
    ["parent"]    = 531,
    ["dbcAreaId"] = 3428,
    ["dbcMapId"]  = 531,
    ["dbcName"]   = "AhnQiraj",
    ["worldBounds"] = { left=2515.63, right=1538.07, top=-8051.80, bottom=-8703.50 },
    ["names"] = { ["enUS"] = "Ahn'Qiraj", ["esES"] = "Ahn'Qiraj", ["ptBR"] = "Ahn'Qiraj", ["zhCN"] = "安其拉" },
  }
end

-- DBC WMA ID=655  MapID=531  'AhnQiraj2f'
if not MTH_DS_Zones[5147] then
  MTH_DS_Zones[5147] = {
    ["continent"] = 531,
    ["parent"]    = 531,
    ["dbcAreaId"] = 5147,
    ["dbcMapId"]  = 531,
    ["dbcName"]   = "AhnQiraj2f",
    ["worldBounds"] = { left=2915.62, right=138.08, top=-7659.29, bottom=-9510.98 },
    ["names"] = { ["enUS"] = "Ahn'Qiraj", ["esES"] = "Ahn'Qiraj", ["ptBR"] = "Ahn'Qiraj", ["zhCN"] = "安其拉" },
  }
end

-- DBC WMA ID=657  MapID=532  'Karazhan'
if not MTH_DS_Zones[3457] then
  MTH_DS_Zones[3457] = {
    ["continent"] = 532,
    ["parent"]    = 532,
    ["dbcAreaId"] = 3457,
    ["dbcMapId"]  = 532,
    ["dbcName"]   = "Karazhan",
    ["worldBounds"] = { left=-1614.00, right=-2212.00, top=-10780.00, bottom=-11179.00 },
    ["names"] = { ["enUS"] = "Tower of Karazhan", ["esES"] = "Torre de Karazhan", ["ptBR"] = "Karazhan", ["zhCN"] = "卡拉赞" },
  }
end

-- DBC WMA ID=659  MapID=369  'DeeprunTram'
if not MTH_DS_Zones[2257] then
  MTH_DS_Zones[2257] = {
    ["continent"] = 369,
    ["parent"]    = 369,
    ["dbcAreaId"] = 2257,
    ["dbcMapId"]  = 369,
    ["dbcName"]   = "DeeprunTram",
    ["worldBounds"] = { left=2623.50, right=2311.50, top=95.50, bottom=-112.50 },
    ["names"] = { ["enUS"] = "Deeprun Tram", ["esES"] = "Tranvía Subterráneo", ["ptBR"] = "Metrô Correfundo", ["zhCN"] = "矿道地铁" },
  }
end

-- DBC WMA ID=660  MapID=369  'DeeprunTram2f'
if not MTH_DS_Zones[5144] then
  MTH_DS_Zones[5144] = {
    ["continent"] = 369,
    ["parent"]    = 369,
    ["dbcAreaId"] = 5144,
    ["dbcMapId"]  = 369,
    ["dbcName"]   = "DeeprunTram2f",
    ["worldBounds"] = { left=187.50, right=-121.50, top=95.50, bottom=-112.50 },
    ["names"] = { ["enUS"] = "Deeprun Tram", ["esES"] = "Tranvía Profundocircuito", ["ptBR"] = "Metrô Correfundo", ["zhCN"] = "矿道地铁" },
  }
end

-- DBC WMA ID=662  MapID=269  'BlackMorass'
if not MTH_DS_Zones[5204] then
  MTH_DS_Zones[5204] = {
    ["continent"] = 269,
    ["parent"]    = 269,
    ["dbcAreaId"] = 5204,
    ["dbcMapId"]  = 269,
    ["dbcName"]   = "BlackMorass",
    ["worldBounds"] = { left=7338.47, right=6066.48, top=-1247.55, bottom=-2093.03 },
    ["names"] = { ["enUS"] = "The Black Morass", ["esES"] = "El Morass Negro", ["ptBR"] = "Lamaçal Negro", ["zhCN"] = "黑色沼泽" },
  }
end

-- DBC WMA ID=663  MapID=269  'BlackMorass2f'
if not MTH_DS_Zones[2366] then
  MTH_DS_Zones[2366] = {
    ["continent"] = 269,
    ["parent"]    = 269,
    ["dbcAreaId"] = 2366,
    ["dbcMapId"]  = 269,
    ["dbcName"]   = "BlackMorass2f",
    ["worldBounds"] = { left=7651.85, right=6565.99, top=-1500.47, bottom=-2227.08 },
    ["names"] = { ["enUS"] = "The Black Morass", ["esES"] = "La Ciénaga Negra", ["ptBR"] = "O Morass Negro", ["zhCN"] = "黑色沼泽" },
  }
end

-- DBC WMA ID=665  MapID=815  'GilneasCity'
if not MTH_DS_Zones[5208] then
  MTH_DS_Zones[5208] = {
    ["continent"] = 815,
    ["parent"]    = 815,
    ["dbcAreaId"] = 5208,
    ["dbcMapId"]  = 815,
    ["dbcName"]   = "GilneasCity",
    ["worldBounds"] = { left=3290.32, right=2040.14, top=-760.72, bottom=-1598.16 },
    ["names"] = { ["enUS"] = "Gilneas City", ["esES"] = "Ciudad Gilneas", ["ptBR"] = "Cidade de Gilneas", ["zhCN"] = "吉尔尼斯城" },
  }
end

-- DBC WMA ID=667  MapID=533  'Naxxramas'
if not MTH_DS_Zones[3456] then
  MTH_DS_Zones[3456] = {
    ["continent"] = 533,
    ["parent"]    = 533,
    ["dbcAreaId"] = 3456,
    ["dbcMapId"]  = 533,
    ["dbcName"]   = "Naxxramas",
    ["worldBounds"] = { left=-2375.27, right=-4366.96, top=3656.70, bottom=2338.28 },
    ["names"] = { ["enUS"] = "Naxxramas", ["esES"] = "Naxxramas", ["ptBR"] = "Naxxramas", ["zhCN"] = "纳克萨玛斯" },
  }
end

-- DBC WMA ID=668  MapID=533  'Naxxramas2f'
if not MTH_DS_Zones[5148] then
  MTH_DS_Zones[5148] = {
    ["continent"] = 533,
    ["parent"]    = 533,
    ["dbcAreaId"] = 5148,
    ["dbcMapId"]  = 533,
    ["dbcName"]   = "Naxxramas2f",
    ["worldBounds"] = { left=-4869.36, right=-5521.46, top=3816.56, bottom=3376.89 },
    ["names"] = { ["enUS"] = "The Upper Necropolis", ["esES"] = "La Necropolis Superior", ["ptBR"] = "Necrópole Superior", ["zhCN"] = "上层大墓地" },
  }
end

-- DBC WMA ID=670  MapID=802  'CrescentGrove'
if not MTH_DS_Zones[5077] then
  MTH_DS_Zones[5077] = {
    ["continent"] = 802,
    ["parent"]    = 802,
    ["dbcAreaId"] = 5077,
    ["dbcMapId"]  = 802,
    ["dbcName"]   = "CrescentGrove",
    ["worldBounds"] = { left=1207.72, right=-1435.49, top=882.98, bottom=-868.18 },
    ["names"] = { ["enUS"] = "Crescent Grove", ["esES"] = "Claro de la Media Luna", ["ptBR"] = "Bosque Crescente", ["zhCN"] = "新月林地" },
  }
end

-- DBC WMA ID=672  MapID=808  'HateforgeQuarry'
if not MTH_DS_Zones[5103] then
  MTH_DS_Zones[5103] = {
    ["continent"] = 808,
    ["parent"]    = 808,
    ["dbcAreaId"] = 5103,
    ["dbcMapId"]  = 808,
    ["dbcName"]   = "HateforgeQuarry",
    ["worldBounds"] = { left=-3024.33, right=-3776.45, top=-7888.28, bottom=-8398.61 },
    ["names"] = { ["enUS"] = "Hateforge Quarry", ["esES"] = "Cantera Hateforge", ["ptBR"] = "Pedreira Forja do Ódio", ["zhCN"] = "仇恨熔炉采石场" },
  }
end

-- DBC WMA ID=674  MapID=800  'KarazhanCrypt'
if not MTH_DS_Zones[5086] then
  MTH_DS_Zones[5086] = {
    ["continent"] = 800,
    ["parent"]    = 800,
    ["dbcAreaId"] = 5086,
    ["dbcMapId"]  = 800,
    ["dbcName"]   = "KarazhanCrypt",
    ["worldBounds"] = { left=-1302.51, right=-1849.26, top=-10916.17, bottom=-11308.14 },
    ["names"] = { ["enUS"] = "Karazhan Crypt", ["esES"] = "Cripta de Karazhan", ["ptBR"] = "Cripta Karazhan", ["zhCN"] = "卡拉赞墓穴" },
  }
end

-- DBC WMA ID=676  MapID=35  'StormwindVault'
if not MTH_DS_Zones[5087] then
  MTH_DS_Zones[5087] = {
    ["continent"] = 35,
    ["parent"]    = 35,
    ["dbcAreaId"] = 5087,
    ["dbcMapId"]  = 35,
    ["dbcName"]   = "StormwindVault",
    ["worldBounds"] = { left=314.34, right=-40.16, top=89.30, bottom=-145.44 },
    ["names"] = { ["enUS"] = "Stormwind Vault", ["esES"] = "Bóveda de Ventormenta", ["ptBR"] = "Cofre Stormwind", ["zhCN"] = "暴风城地牢" },
  }
end

-- DBC WMA ID=678  MapID=807  'EmeraldSanctum'
if not MTH_DS_Zones[5097] then
  MTH_DS_Zones[5097] = {
    ["continent"] = 807,
    ["parent"]    = 807,
    ["dbcAreaId"] = 5097,
    ["dbcMapId"]  = 807,
    ["dbcName"]   = "EmeraldSanctum",
    ["worldBounds"] = { left=3939.10, right=2666.00, top=3519.72, bottom=2666.00 },
    ["names"] = { ["enUS"] = "Emerald Sanctum", ["esES"] = "Sanctum Esmeralda", ["ptBR"] = "Santuário Esmeralda", ["zhCN"] = "翡翠圣殿" },
  }
end

-- DBC WMA ID=680  MapID=801  'Moomoo'
if not MTH_DS_Zones[5053] then
  MTH_DS_Zones[5053] = {
    ["continent"] = 801,
    ["parent"]    = 801,
    ["dbcAreaId"] = 5053,
    ["dbcMapId"]  = 801,
    ["dbcName"]   = "Moomoo",
    ["worldBounds"] = { left=17296.30, right=16288.62, top=17158.52, bottom=16486.73 },
    ["names"] = { ["enUS"] = "Moomoo Grove", ["esES"] = "Claro Moomoo", ["ptBR"] = "Bosque Moomoo", ["zhCN"] = "奶牛树林" },
  }
end

-- DBC WMA ID=682  MapID=814  'UpperKarazhan'
if not MTH_DS_Zones[3457] then
  MTH_DS_Zones[3457] = {
    ["continent"] = 814,
    ["parent"]    = 814,
    ["dbcAreaId"] = 3457,
    ["dbcMapId"]  = 814,
    ["dbcName"]   = "UpperKarazhan",
    ["worldBounds"] = { left=-1378.00, right=-2201.00, top=-10887.00, bottom=-11436.00 },
    ["names"] = { ["enUS"] = "Tower of Karazhan", ["esES"] = "Torre de Karazhan", ["ptBR"] = "Karazhan", ["zhCN"] = "卡拉赞" },
  }
end

-- DBC WMA ID=683  MapID=814  'UpperKarazhan2f'
if not MTH_DS_Zones[5557] then
  MTH_DS_Zones[5557] = {
    ["continent"] = 814,
    ["parent"]    = 814,
    ["dbcAreaId"] = 5557,
    ["dbcMapId"]  = 814,
    ["dbcName"]   = "UpperKarazhan2f",
    ["worldBounds"] = { left=-1483.00, right=-4283.00, top=-5800.00, bottom=-7668.00 },
    ["names"] = { ["enUS"] = "???", ["esES"] = "???", ["ptBR"] = "???", ["zhCN"] = "外域" },
  }
end
