MTH_CONST = MTH_CONST or {}
MTH_CONST.version = MTH_CONST.version or "1.0.4"

MTH_CONST.WEAPON_TYPES = {
	BOWS = "Bows",
	CROSSBOWS = "Crossbows",
	GUNS = "Guns",
}

MTH_CONST.AMMO = {
	BULLETS = {
		LIGHT = "Light Shot",
		CRAFTLIGHT = "Crafted Light Shot",
		FLASH = "Flash Pellet",
		HEAVY = "Heavy Shot",
		PEBBLE = "Smooth Pebble",
		CRAFTHEAVY = "Crafted Heavy Shot",
		SOLID = "Solid Shot",
		CRAFTSOLID = "Crafted Solid Shot",
		EXPLODING = "Exploding Shot",
		MITHRILSLUG = "Hi-Impact Mithril Slugs",
		ACCURATE = "Accurate Slugs",
		GYROSHOT = "Mithril Gyro-Shot",
		ICETHREADED = "Ice Threaded Bullet",
		THORIUM = "Thorium Shells",
		ROCKSHARD = "Rockshard Pellets",
		CANNONBALL = "Miniature Cannon Balls",
	},
	ARROWS = {
		ROUGH = "Rough Arrow",
		SHARP = "Sharp Arrow",
		RAZOR = "Razor Arrow",
		FEATHER = "Feathered Arrow",
		PRECISION = "Precision Arrow",
		JAGGED = "Jagged Arrow",
		ICETHREADED = "Ice Threaded Arrow",
		THORIUM = "Thorium Headed Arrow",
		DOOMSHOT = "Doomshot",
	},
	JUNKSHOTS = {
		SERPENT = "Serpent Sting",
		SCORPID = "Scorpid Sting",
		VIPER = "Viper Sting",
		ARCANE = "Arcane Shot",
		CONCUSSIVE = "Concussive Shot",
		DISTRACTING = "Distracting Shot",
        BAITED = "Baited Shot",
        TRANQ = "Tranquilizing Shot",
	},
}

MTH_WEAPON_BOWS = MTH_CONST.WEAPON_TYPES.BOWS
MTH_WEAPON_CROSSBOWS = MTH_CONST.WEAPON_TYPES.CROSSBOWS
MTH_WEAPON_GUNS = MTH_CONST.WEAPON_TYPES.GUNS

BULLETS_LIGHT = MTH_CONST.AMMO.BULLETS.LIGHT
BULLETS_CRAFTLIGHT = MTH_CONST.AMMO.BULLETS.CRAFTLIGHT
BULLETS_FLASH = MTH_CONST.AMMO.BULLETS.FLASH
BULLETS_HEAVY = MTH_CONST.AMMO.BULLETS.HEAVY
BULLETS_PEBBLE = MTH_CONST.AMMO.BULLETS.PEBBLE
BULLETS_CRAFTHEAVY = MTH_CONST.AMMO.BULLETS.CRAFTHEAVY
BULLETS_SOLID = MTH_CONST.AMMO.BULLETS.SOLID
BULLETS_CRAFTSOLID = MTH_CONST.AMMO.BULLETS.CRAFTSOLID
BULLETS_EXPLODING = MTH_CONST.AMMO.BULLETS.EXPLODING
BULLETS_MITHRILSLUG = MTH_CONST.AMMO.BULLETS.MITHRILSLUG
BULLETS_ACCURATE = MTH_CONST.AMMO.BULLETS.ACCURATE
BULLETS_GYROSHOT = MTH_CONST.AMMO.BULLETS.GYROSHOT
BULLETS_ICETHREADED = MTH_CONST.AMMO.BULLETS.ICETHREADED
BULLETS_THORIUM = MTH_CONST.AMMO.BULLETS.THORIUM
BULLETS_ROCKSHARD = MTH_CONST.AMMO.BULLETS.ROCKSHARD
BULLETS_CANNONBALL = MTH_CONST.AMMO.BULLETS.CANNONBALL

ARROWS_ROUGH = MTH_CONST.AMMO.ARROWS.ROUGH
ARROWS_SHARP = MTH_CONST.AMMO.ARROWS.SHARP
ARROWS_RAZOR = MTH_CONST.AMMO.ARROWS.RAZOR
ARROWS_FEATHER = MTH_CONST.AMMO.ARROWS.FEATHER
ARROWS_PRECISION = MTH_CONST.AMMO.ARROWS.PRECISION
ARROWS_JAGGED = MTH_CONST.AMMO.ARROWS.JAGGED
ARROWS_ICETHREADED = MTH_CONST.AMMO.ARROWS.ICETHREADED
ARROWS_THORIUM = MTH_CONST.AMMO.ARROWS.THORIUM
ARROWS_DOOMSHOT = MTH_CONST.AMMO.ARROWS.DOOMSHOT

JUNKSHOT_SERPENT = MTH_CONST.AMMO.JUNKSHOTS.SERPENT
JUNKSHOT_SCORPID = MTH_CONST.AMMO.JUNKSHOTS.SCORPID
JUNKSHOT_VIPER = MTH_CONST.AMMO.JUNKSHOTS.VIPER
JUNKSHOT_ARCANE = MTH_CONST.AMMO.JUNKSHOTS.ARCANE
JUNKSHOT_CONCUSSIVE = MTH_CONST.AMMO.JUNKSHOTS.CONCUSSIVE
JUNKSHOT_DISTRACTING = MTH_CONST.AMMO.JUNKSHOTS.DISTRACTING
JUNKSHOT_BAITED = MTH_CONST.AMMO.JUNKSHOTS.BAITED
JUNKSHOT_TRANQ = MTH_CONST.AMMO.JUNKSHOTS.TRANQ

MTH_AMMO_BULLETS = {
	BULLETS_LIGHT,
	BULLETS_CRAFTLIGHT,
	BULLETS_FLASH,
	BULLETS_HEAVY,
	BULLETS_PEBBLE,
	BULLETS_CRAFTHEAVY,
	BULLETS_SOLID,
	BULLETS_CRAFTSOLID,
	BULLETS_EXPLODING,
	BULLETS_MITHRILSLUG,
	BULLETS_ACCURATE,
	BULLETS_GYROSHOT,
	BULLETS_ICETHREADED,
	BULLETS_THORIUM,
	BULLETS_ROCKSHARD,
	BULLETS_CANNONBALL,
}

MTH_AMMO_ARROWS = {
	ARROWS_ROUGH,
	ARROWS_SHARP,
	ARROWS_RAZOR,
	ARROWS_FEATHER,
	ARROWS_PRECISION,
	ARROWS_JAGGED,
	ARROWS_ICETHREADED,
	ARROWS_THORIUM,
	ARROWS_DOOMSHOT,
}

MTH_AMMO_JUNKSHOTS = {
	JUNKSHOT_SERPENT,
	JUNKSHOT_SCORPID,
	JUNKSHOT_VIPER,
	JUNKSHOT_ARCANE,
	JUNKSHOT_CONCUSSIVE,
	JUNKSHOT_DISTRACTING,
	JUNKSHOT_BAITED,
	JUNKSHOT_TRANQ,
}

MTH_AMMO_BULLET_RANK = {}
for i = 1, table.getn(MTH_AMMO_BULLETS) do
	local ammoName = MTH_AMMO_BULLETS[i]
	if ammoName then
		MTH_AMMO_BULLET_RANK[ammoName] = i
	end
end

MTH_AMMO_ARROW_RANK = {}
for i = 1, table.getn(MTH_AMMO_ARROWS) do
	local ammoName = MTH_AMMO_ARROWS[i]
	if ammoName then
		MTH_AMMO_ARROW_RANK[ammoName] = i
	end
end

MTH_AMMO_JUNKSHOT_SET = {}
for i = 1, table.getn(MTH_AMMO_JUNKSHOTS) do
	local spellName = MTH_AMMO_JUNKSHOTS[i]
	if spellName then
		MTH_AMMO_JUNKSHOT_SET[spellName] = 1
	end
end
